// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fredsaggio/bondrota-api/internal/admin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAdminStore creates a new instance of MockAdminStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminStore {
	mock := &MockAdminStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdminStore is an autogenerated mock type for the AdminStore type
type MockAdminStore struct {
	mock.Mock
}

type MockAdminStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminStore) EXPECT() *MockAdminStore_Expecter {
	return &MockAdminStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAdminStore
func (_mock *MockAdminStore) Create(ctx context.Context, input admin.AdminInput) (*admin.Admin, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *admin.Admin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, admin.AdminInput) (*admin.Admin, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, admin.AdminInput) *admin.Admin); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.Admin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, admin.AdminInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAdminStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input admin.AdminInput
func (_e *MockAdminStore_Expecter) Create(ctx interface{}, input interface{}) *MockAdminStore_Create_Call {
	return &MockAdminStore_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockAdminStore_Create_Call) Run(run func(ctx context.Context, input admin.AdminInput)) *MockAdminStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 admin.AdminInput
		if args[1] != nil {
			arg1 = args[1].(admin.AdminInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminStore_Create_Call) Return(admin1 *admin.Admin, err error) *MockAdminStore_Create_Call {
	_c.Call.Return(admin1, err)
	return _c
}

func (_c *MockAdminStore_Create_Call) RunAndReturn(run func(ctx context.Context, input admin.AdminInput) (*admin.Admin, error)) *MockAdminStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockAdminStore
func (_mock *MockAdminStore) Delete(ctx context.Context, adminID int64) error {
	ret := _mock.Called(ctx, adminID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, adminID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdminStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAdminStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID int64
func (_e *MockAdminStore_Expecter) Delete(ctx interface{}, adminID interface{}) *MockAdminStore_Delete_Call {
	return &MockAdminStore_Delete_Call{Call: _e.mock.On("Delete", ctx, adminID)}
}

func (_c *MockAdminStore_Delete_Call) Run(run func(ctx context.Context, adminID int64)) *MockAdminStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminStore_Delete_Call) Return(err error) *MockAdminStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdminStore_Delete_Call) RunAndReturn(run func(ctx context.Context, adminID int64) error) *MockAdminStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type MockAdminStore
func (_mock *MockAdminStore) GetByEmail(ctx context.Context, email string) (*admin.Admin, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *admin.Admin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*admin.Admin, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *admin.Admin); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.Admin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminStore_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockAdminStore_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAdminStore_Expecter) GetByEmail(ctx interface{}, email interface{}) *MockAdminStore_GetByEmail_Call {
	return &MockAdminStore_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockAdminStore_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockAdminStore_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminStore_GetByEmail_Call) Return(admin1 *admin.Admin, err error) *MockAdminStore_GetByEmail_Call {
	_c.Call.Return(admin1, err)
	return _c
}

func (_c *MockAdminStore_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*admin.Admin, error)) *MockAdminStore_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockAdminStore
func (_mock *MockAdminStore) GetByID(ctx context.Context, adminID int64) (*admin.Admin, error) {
	ret := _mock.Called(ctx, adminID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *admin.Admin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*admin.Admin, error)); ok {
		return returnFunc(ctx, adminID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *admin.Admin); ok {
		r0 = returnFunc(ctx, adminID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.Admin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, adminID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAdminStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID int64
func (_e *MockAdminStore_Expecter) GetByID(ctx interface{}, adminID interface{}) *MockAdminStore_GetByID_Call {
	return &MockAdminStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, adminID)}
}

func (_c *MockAdminStore_GetByID_Call) Run(run func(ctx context.Context, adminID int64)) *MockAdminStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAdminStore_GetByID_Call) Return(admin1 *admin.Admin, err error) *MockAdminStore_GetByID_Call {
	_c.Call.Return(admin1, err)
	return _c
}

func (_c *MockAdminStore_GetByID_Call) RunAndReturn(run func(ctx context.Context, adminID int64) (*admin.Admin, error)) *MockAdminStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockAdminStore
func (_mock *MockAdminStore) List(ctx context.Context) ([]admin.Admin, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []admin.Admin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]admin.Admin, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []admin.Admin); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]admin.Admin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAdminStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAdminStore_Expecter) List(ctx interface{}) *MockAdminStore_List_Call {
	return &MockAdminStore_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockAdminStore_List_Call) Run(run func(ctx context.Context)) *MockAdminStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAdminStore_List_Call) Return(admins []admin.Admin, err error) *MockAdminStore_List_Call {
	_c.Call.Return(admins, err)
	return _c
}

func (_c *MockAdminStore_List_Call) RunAndReturn(run func(ctx context.Context) ([]admin.Admin, error)) *MockAdminStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockAdminStore
func (_mock *MockAdminStore) Update(ctx context.Context, adminID int64, updateFunc func(*admin.Admin) (bool, error)) (*admin.Admin, error) {
	ret := _mock.Called(ctx, adminID, updateFunc)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *admin.Admin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, func(*admin.Admin) (bool, error)) (*admin.Admin, error)); ok {
		return returnFunc(ctx, adminID, updateFunc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, func(*admin.Admin) (bool, error)) *admin.Admin); ok {
		r0 = returnFunc(ctx, adminID, updateFunc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.Admin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, func(*admin.Admin) (bool, error)) error); ok {
		r1 = returnFunc(ctx, adminID, updateFunc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAdminStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - adminID int64
//   - updateFunc func(*admin.Admin) (bool, error)
func (_e *MockAdminStore_Expecter) Update(ctx interface{}, adminID interface{}, updateFunc interface{}) *MockAdminStore_Update_Call {
	return &MockAdminStore_Update_Call{Call: _e.mock.On("Update", ctx, adminID, updateFunc)}
}

func (_c *MockAdminStore_Update_Call) Run(run func(ctx context.Context, adminID int64, updateFunc func(*admin.Admin) (bool, error))) *MockAdminStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 func(*admin.Admin) (bool, error)
		if args[2] != nil {
			arg2 = args[2].(func(*admin.Admin) (bool, error))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdminStore_Update_Call) Return(admin1 *admin.Admin, err error) *MockAdminStore_Update_Call {
	_c.Call.Return(admin1, err)
	return _c
}

func (_c *MockAdminStore_Update_Call) RunAndReturn(run func(ctx context.Context, adminID int64, updateFunc func(*admin.Admin) (bool, error)) (*admin.Admin, error)) *MockAdminStore_Update_Call {
	_c.Call.Return(run)
	return _c
}
