// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fredsaggio/bondrota-api/internal/clientes"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClienteStore creates a new instance of MockClienteStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClienteStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClienteStore {
	mock := &MockClienteStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClienteStore is an autogenerated mock type for the ClienteStore type
type MockClienteStore struct {
	mock.Mock
}

type MockClienteStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClienteStore) EXPECT() *MockClienteStore_Expecter {
	return &MockClienteStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockClienteStore
func (_mock *MockClienteStore) Create(ctx context.Context, input clientes.ClienteInput) (*clientes.Cliente, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *clientes.Cliente
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, clientes.ClienteInput) (*clientes.Cliente, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, clientes.ClienteInput) *clientes.Cliente); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientes.Cliente)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, clientes.ClienteInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClienteStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockClienteStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input clientes.ClienteInput
func (_e *MockClienteStore_Expecter) Create(ctx interface{}, input interface{}) *MockClienteStore_Create_Call {
	return &MockClienteStore_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockClienteStore_Create_Call) Run(run func(ctx context.Context, input clientes.ClienteInput)) *MockClienteStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 clientes.ClienteInput
		if args[1] != nil {
			arg1 = args[1].(clientes.ClienteInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClienteStore_Create_Call) Return(cliente *clientes.Cliente, err error) *MockClienteStore_Create_Call {
	_c.Call.Return(cliente, err)
	return _c
}

func (_c *MockClienteStore_Create_Call) RunAndReturn(run func(ctx context.Context, input clientes.ClienteInput) (*clientes.Cliente, error)) *MockClienteStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockClienteStore
func (_mock *MockClienteStore) Delete(ctx context.Context, clienteID int64) error {
	ret := _mock.Called(ctx, clienteID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, clienteID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClienteStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockClienteStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - clienteID int64
func (_e *MockClienteStore_Expecter) Delete(ctx interface{}, clienteID interface{}) *MockClienteStore_Delete_Call {
	return &MockClienteStore_Delete_Call{Call: _e.mock.On("Delete", ctx, clienteID)}
}

func (_c *MockClienteStore_Delete_Call) Run(run func(ctx context.Context, clienteID int64)) *MockClienteStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClienteStore_Delete_Call) Return(err error) *MockClienteStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClienteStore_Delete_Call) RunAndReturn(run func(ctx context.Context, clienteID int64) error) *MockClienteStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCPF provides a mock function for the type MockClienteStore
func (_mock *MockClienteStore) GetByCPF(ctx context.Context, cpf string) (*clientes.Cliente, error) {
	ret := _mock.Called(ctx, cpf)

	if len(ret) == 0 {
		panic("no return value specified for GetByCPF")
	}

	var r0 *clientes.Cliente
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*clientes.Cliente, error)); ok {
		return returnFunc(ctx, cpf)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *clientes.Cliente); ok {
		r0 = returnFunc(ctx, cpf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientes.Cliente)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, cpf)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClienteStore_GetByCPF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCPF'
type MockClienteStore_GetByCPF_Call struct {
	*mock.Call
}

// GetByCPF is a helper method to define mock.On call
//   - ctx context.Context
//   - cpf string
func (_e *MockClienteStore_Expecter) GetByCPF(ctx interface{}, cpf interface{}) *MockClienteStore_GetByCPF_Call {
	return &MockClienteStore_GetByCPF_Call{Call: _e.mock.On("GetByCPF", ctx, cpf)}
}

func (_c *MockClienteStore_GetByCPF_Call) Run(run func(ctx context.Context, cpf string)) *MockClienteStore_GetByCPF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClienteStore_GetByCPF_Call) Return(cliente *clientes.Cliente, err error) *MockClienteStore_GetByCPF_Call {
	_c.Call.Return(cliente, err)
	return _c
}

func (_c *MockClienteStore_GetByCPF_Call) RunAndReturn(run func(ctx context.Context, cpf string) (*clientes.Cliente, error)) *MockClienteStore_GetByCPF_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockClienteStore
func (_mock *MockClienteStore) GetByID(ctx context.Context, clienteID int64) (*clientes.ClienteComVinculos, error) {
	ret := _mock.Called(ctx, clienteID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *clientes.ClienteComVinculos
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*clientes.ClienteComVinculos, error)); ok {
		return returnFunc(ctx, clienteID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *clientes.ClienteComVinculos); ok {
		r0 = returnFunc(ctx, clienteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientes.ClienteComVinculos)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, clienteID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClienteStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockClienteStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - clienteID int64
func (_e *MockClienteStore_Expecter) GetByID(ctx interface{}, clienteID interface{}) *MockClienteStore_GetByID_Call {
	return &MockClienteStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, clienteID)}
}

func (_c *MockClienteStore_GetByID_Call) Run(run func(ctx context.Context, clienteID int64)) *MockClienteStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClienteStore_GetByID_Call) Return(clienteComVinculos *clientes.ClienteComVinculos, err error) *MockClienteStore_GetByID_Call {
	_c.Call.Return(clienteComVinculos, err)
	return _c
}

func (_c *MockClienteStore_GetByID_Call) RunAndReturn(run func(ctx context.Context, clienteID int64) (*clientes.ClienteComVinculos, error)) *MockClienteStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockClienteStore
func (_mock *MockClienteStore) List(ctx context.Context, params clientes.ClienteListParams) (clientes.ClienteListResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 clientes.ClienteListResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, clientes.ClienteListParams) (clientes.ClienteListResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, clientes.ClienteListParams) clientes.ClienteListResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(clientes.ClienteListResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, clientes.ClienteListParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClienteStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockClienteStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - params clientes.ClienteListParams
func (_e *MockClienteStore_Expecter) List(ctx interface{}, params interface{}) *MockClienteStore_List_Call {
	return &MockClienteStore_List_Call{Call: _e.mock.On("List", ctx, params)}
}

func (_c *MockClienteStore_List_Call) Run(run func(ctx context.Context, params clientes.ClienteListParams)) *MockClienteStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 clientes.ClienteListParams
		if args[1] != nil {
			arg1 = args[1].(clientes.ClienteListParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClienteStore_List_Call) Return(clienteListResult clientes.ClienteListResult, err error) *MockClienteStore_List_Call {
	_c.Call.Return(clienteListResult, err)
	return _c
}

func (_c *MockClienteStore_List_Call) RunAndReturn(run func(ctx context.Context, params clientes.ClienteListParams) (clientes.ClienteListResult, error)) *MockClienteStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Resumo provides a mock function for the type MockClienteStore
func (_mock *MockClienteStore) Resumo(ctx context.Context) (clientes.ClienteResumo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Resumo")
	}

	var r0 clientes.ClienteResumo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (clientes.ClienteResumo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) clientes.ClienteResumo); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(clientes.ClienteResumo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClienteStore_Resumo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resumo'
type MockClienteStore_Resumo_Call struct {
	*mock.Call
}

// Resumo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClienteStore_Expecter) Resumo(ctx interface{}) *MockClienteStore_Resumo_Call {
	return &MockClienteStore_Resumo_Call{Call: _e.mock.On("Resumo", ctx)}
}

func (_c *MockClienteStore_Resumo_Call) Run(run func(ctx context.Context)) *MockClienteStore_Resumo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClienteStore_Resumo_Call) Return(clienteResumo clientes.ClienteResumo, err error) *MockClienteStore_Resumo_Call {
	_c.Call.Return(clienteResumo, err)
	return _c
}

func (_c *MockClienteStore_Resumo_Call) RunAndReturn(run func(ctx context.Context) (clientes.ClienteResumo, error)) *MockClienteStore_Resumo_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockClienteStore
func (_mock *MockClienteStore) Update(ctx context.Context, clienteID int64, updateFunc func(*clientes.Cliente) (bool, error)) (*clientes.Cliente, error) {
	ret := _mock.Called(ctx, clienteID, updateFunc)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *clientes.Cliente
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, func(*clientes.Cliente) (bool, error)) (*clientes.Cliente, error)); ok {
		return returnFunc(ctx, clienteID, updateFunc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, func(*clientes.Cliente) (bool, error)) *clientes.Cliente); ok {
		r0 = returnFunc(ctx, clienteID, updateFunc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientes.Cliente)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, func(*clientes.Cliente) (bool, error)) error); ok {
		r1 = returnFunc(ctx, clienteID, updateFunc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClienteStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockClienteStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - clienteID int64
//   - updateFunc func(*clientes.Cliente) (bool, error)
func (_e *MockClienteStore_Expecter) Update(ctx interface{}, clienteID interface{}, updateFunc interface{}) *MockClienteStore_Update_Call {
	return &MockClienteStore_Update_Call{Call: _e.mock.On("Update", ctx, clienteID, updateFunc)}
}

func (_c *MockClienteStore_Update_Call) Run(run func(ctx context.Context, clienteID int64, updateFunc func(*clientes.Cliente) (bool, error))) *MockClienteStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 func(*clientes.Cliente) (bool, error)
		if args[2] != nil {
			arg2 = args[2].(func(*clientes.Cliente) (bool, error))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClienteStore_Update_Call) Return(cliente *clientes.Cliente, err error) *MockClienteStore_Update_Call {
	_c.Call.Return(cliente, err)
	return _c
}

func (_c *MockClienteStore_Update_Call) RunAndReturn(run func(ctx context.Context, clienteID int64, updateFunc func(*clientes.Cliente) (bool, error)) (*clientes.Cliente, error)) *MockClienteStore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVinculoStore creates a new instance of MockVinculoStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVinculoStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVinculoStore {
	mock := &MockVinculoStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVinculoStore is an autogenerated mock type for the VinculoStore type
type MockVinculoStore struct {
	mock.Mock
}

type MockVinculoStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVinculoStore) EXPECT() *MockVinculoStore_Expecter {
	return &MockVinculoStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockVinculoStore
func (_mock *MockVinculoStore) Create(ctx context.Context, input clientes.VinculoInput) (*clientes.Vinculo, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *clientes.Vinculo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, clientes.VinculoInput) (*clientes.Vinculo, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, clientes.VinculoInput) *clientes.Vinculo); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientes.Vinculo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, clientes.VinculoInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVinculoStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockVinculoStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input clientes.VinculoInput
func (_e *MockVinculoStore_Expecter) Create(ctx interface{}, input interface{}) *MockVinculoStore_Create_Call {
	return &MockVinculoStore_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockVinculoStore_Create_Call) Run(run func(ctx context.Context, input clientes.VinculoInput)) *MockVinculoStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 clientes.VinculoInput
		if args[1] != nil {
			arg1 = args[1].(clientes.VinculoInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVinculoStore_Create_Call) Return(vinculo *clientes.Vinculo, err error) *MockVinculoStore_Create_Call {
	_c.Call.Return(vinculo, err)
	return _c
}

func (_c *MockVinculoStore_Create_Call) RunAndReturn(run func(ctx context.Context, input clientes.VinculoInput) (*clientes.Vinculo, error)) *MockVinculoStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockVinculoStore
func (_mock *MockVinculoStore) Delete(ctx context.Context, vinculoID int64) error {
	ret := _mock.Called(ctx, vinculoID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, vinculoID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVinculoStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockVinculoStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - vinculoID int64
func (_e *MockVinculoStore_Expecter) Delete(ctx interface{}, vinculoID interface{}) *MockVinculoStore_Delete_Call {
	return &MockVinculoStore_Delete_Call{Call: _e.mock.On("Delete", ctx, vinculoID)}
}

func (_c *MockVinculoStore_Delete_Call) Run(run func(ctx context.Context, vinculoID int64)) *MockVinculoStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVinculoStore_Delete_Call) Return(err error) *MockVinculoStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVinculoStore_Delete_Call) RunAndReturn(run func(ctx context.Context, vinculoID int64) error) *MockVinculoStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockVinculoStore
func (_mock *MockVinculoStore) GetByID(ctx context.Context, vinculoID int64) (*clientes.Vinculo, error) {
	ret := _mock.Called(ctx, vinculoID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *clientes.Vinculo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*clientes.Vinculo, error)); ok {
		return returnFunc(ctx, vinculoID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *clientes.Vinculo); ok {
		r0 = returnFunc(ctx, vinculoID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientes.Vinculo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, vinculoID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVinculoStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockVinculoStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - vinculoID int64
func (_e *MockVinculoStore_Expecter) GetByID(ctx interface{}, vinculoID interface{}) *MockVinculoStore_GetByID_Call {
	return &MockVinculoStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, vinculoID)}
}

func (_c *MockVinculoStore_GetByID_Call) Run(run func(ctx context.Context, vinculoID int64)) *MockVinculoStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVinculoStore_GetByID_Call) Return(vinculo *clientes.Vinculo, err error) *MockVinculoStore_GetByID_Call {
	_c.Call.Return(vinculo, err)
	return _c
}

func (_c *MockVinculoStore_GetByID_Call) RunAndReturn(run func(ctx context.Context, vinculoID int64) (*clientes.Vinculo, error)) *MockVinculoStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockVinculoStore
func (_mock *MockVinculoStore) List(ctx context.Context, params clientes.VinculoListParams) (clientes.VinculoListResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 clientes.VinculoListResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, clientes.VinculoListParams) (clientes.VinculoListResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, clientes.VinculoListParams) clientes.VinculoListResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(clientes.VinculoListResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, clientes.VinculoListParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVinculoStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockVinculoStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - params clientes.VinculoListParams
func (_e *MockVinculoStore_Expecter) List(ctx interface{}, params interface{}) *MockVinculoStore_List_Call {
	return &MockVinculoStore_List_Call{Call: _e.mock.On("List", ctx, params)}
}

func (_c *MockVinculoStore_List_Call) Run(run func(ctx context.Context, params clientes.VinculoListParams)) *MockVinculoStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 clientes.VinculoListParams
		if args[1] != nil {
			arg1 = args[1].(clientes.VinculoListParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVinculoStore_List_Call) Return(vinculoListResult clientes.VinculoListResult, err error) *MockVinculoStore_List_Call {
	_c.Call.Return(vinculoListResult, err)
	return _c
}

func (_c *MockVinculoStore_List_Call) RunAndReturn(run func(ctx context.Context, params clientes.VinculoListParams) (clientes.VinculoListResult, error)) *MockVinculoStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCliente provides a mock function for the type MockVinculoStore
func (_mock *MockVinculoStore) ListByCliente(ctx context.Context, clienteID int64) ([]clientes.Vinculo, error) {
	ret := _mock.Called(ctx, clienteID)

	if len(ret) == 0 {
		panic("no return value specified for ListByCliente")
	}

	var r0 []clientes.Vinculo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]clientes.Vinculo, error)); ok {
		return returnFunc(ctx, clienteID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []clientes.Vinculo); ok {
		r0 = returnFunc(ctx, clienteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]clientes.Vinculo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, clienteID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVinculoStore_ListByCliente_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCliente'
type MockVinculoStore_ListByCliente_Call struct {
	*mock.Call
}

// ListByCliente is a helper method to define mock.On call
//   - ctx context.Context
//   - clienteID int64
func (_e *MockVinculoStore_Expecter) ListByCliente(ctx interface{}, clienteID interface{}) *MockVinculoStore_ListByCliente_Call {
	return &MockVinculoStore_ListByCliente_Call{Call: _e.mock.On("ListByCliente", ctx, clienteID)}
}

func (_c *MockVinculoStore_ListByCliente_Call) Run(run func(ctx context.Context, clienteID int64)) *MockVinculoStore_ListByCliente_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVinculoStore_ListByCliente_Call) Return(vinculos []clientes.Vinculo, err error) *MockVinculoStore_ListByCliente_Call {
	_c.Call.Return(vinculos, err)
	return _c
}

func (_c *MockVinculoStore_ListByCliente_Call) RunAndReturn(run func(ctx context.Context, clienteID int64) ([]clientes.Vinculo, error)) *MockVinculoStore_ListByCliente_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockVinculoStore
func (_mock *MockVinculoStore) Update(ctx context.Context, vinculoID int64, input clientes.VinculoUpdateInput) (*clientes.Vinculo, error) {
	ret := _mock.Called(ctx, vinculoID, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *clientes.Vinculo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, clientes.VinculoUpdateInput) (*clientes.Vinculo, error)); ok {
		return returnFunc(ctx, vinculoID, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, clientes.VinculoUpdateInput) *clientes.Vinculo); ok {
		r0 = returnFunc(ctx, vinculoID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*clientes.Vinculo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, clientes.VinculoUpdateInput) error); ok {
		r1 = returnFunc(ctx, vinculoID, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVinculoStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockVinculoStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - vinculoID int64
//   - input clientes.VinculoUpdateInput
func (_e *MockVinculoStore_Expecter) Update(ctx interface{}, vinculoID interface{}, input interface{}) *MockVinculoStore_Update_Call {
	return &MockVinculoStore_Update_Call{Call: _e.mock.On("Update", ctx, vinculoID, input)}
}

func (_c *MockVinculoStore_Update_Call) Run(run func(ctx context.Context, vinculoID int64, input clientes.VinculoUpdateInput)) *MockVinculoStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 clientes.VinculoUpdateInput
		if args[2] != nil {
			arg2 = args[2].(clientes.VinculoUpdateInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVinculoStore_Update_Call) Return(vinculo *clientes.Vinculo, err error) *MockVinculoStore_Update_Call {
	_c.Call.Return(vinculo, err)
	return _c
}

func (_c *MockVinculoStore_Update_Call) RunAndReturn(run func(ctx context.Context, vinculoID int64, input clientes.VinculoUpdateInput) (*clientes.Vinculo, error)) *MockVinculoStore_Update_Call {
	_c.Call.Return(run)
	return _c
}
