// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fredsaggio/bondrota-api/internal/destinos"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDestinoStore creates a new instance of MockDestinoStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDestinoStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDestinoStore {
	mock := &MockDestinoStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDestinoStore is an autogenerated mock type for the DestinoStore type
type MockDestinoStore struct {
	mock.Mock
}

type MockDestinoStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDestinoStore) EXPECT() *MockDestinoStore_Expecter {
	return &MockDestinoStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockDestinoStore
func (_mock *MockDestinoStore) Create(ctx context.Context, input destinos.DestinoInput) (*destinos.Destino, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *destinos.Destino
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, destinos.DestinoInput) (*destinos.Destino, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, destinos.DestinoInput) *destinos.Destino); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*destinos.Destino)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, destinos.DestinoInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDestinoStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDestinoStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input destinos.DestinoInput
func (_e *MockDestinoStore_Expecter) Create(ctx interface{}, input interface{}) *MockDestinoStore_Create_Call {
	return &MockDestinoStore_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockDestinoStore_Create_Call) Run(run func(ctx context.Context, input destinos.DestinoInput)) *MockDestinoStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 destinos.DestinoInput
		if args[1] != nil {
			arg1 = args[1].(destinos.DestinoInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDestinoStore_Create_Call) Return(destino *destinos.Destino, err error) *MockDestinoStore_Create_Call {
	_c.Call.Return(destino, err)
	return _c
}

func (_c *MockDestinoStore_Create_Call) RunAndReturn(run func(ctx context.Context, input destinos.DestinoInput) (*destinos.Destino, error)) *MockDestinoStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockDestinoStore
func (_mock *MockDestinoStore) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDestinoStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDestinoStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockDestinoStore_Expecter) Delete(ctx interface{}, id interface{}) *MockDestinoStore_Delete_Call {
	return &MockDestinoStore_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockDestinoStore_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockDestinoStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDestinoStore_Delete_Call) Return(err error) *MockDestinoStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDestinoStore_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockDestinoStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockDestinoStore
func (_mock *MockDestinoStore) GetByID(ctx context.Context, id int64) (*destinos.Destino, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *destinos.Destino
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*destinos.Destino, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *destinos.Destino); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*destinos.Destino)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDestinoStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockDestinoStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockDestinoStore_Expecter) GetByID(ctx interface{}, id interface{}) *MockDestinoStore_GetByID_Call {
	return &MockDestinoStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockDestinoStore_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockDestinoStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDestinoStore_GetByID_Call) Return(destino *destinos.Destino, err error) *MockDestinoStore_GetByID_Call {
	_c.Call.Return(destino, err)
	return _c
}

func (_c *MockDestinoStore_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*destinos.Destino, error)) *MockDestinoStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockDestinoStore
func (_mock *MockDestinoStore) List(ctx context.Context) ([]destinos.Destino, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []destinos.Destino
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]destinos.Destino, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []destinos.Destino); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]destinos.Destino)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDestinoStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDestinoStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDestinoStore_Expecter) List(ctx interface{}) *MockDestinoStore_List_Call {
	return &MockDestinoStore_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockDestinoStore_List_Call) Run(run func(ctx context.Context)) *MockDestinoStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDestinoStore_List_Call) Return(destinos1 []destinos.Destino, err error) *MockDestinoStore_List_Call {
	_c.Call.Return(destinos1, err)
	return _c
}

func (_c *MockDestinoStore_List_Call) RunAndReturn(run func(ctx context.Context) ([]destinos.Destino, error)) *MockDestinoStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByMunicipio provides a mock function for the type MockDestinoStore
func (_mock *MockDestinoStore) ListByMunicipio(ctx context.Context, municipioID int64) ([]destinos.Destino, error) {
	ret := _mock.Called(ctx, municipioID)

	if len(ret) == 0 {
		panic("no return value specified for ListByMunicipio")
	}

	var r0 []destinos.Destino
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]destinos.Destino, error)); ok {
		return returnFunc(ctx, municipioID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []destinos.Destino); ok {
		r0 = returnFunc(ctx, municipioID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]destinos.Destino)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, municipioID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDestinoStore_ListByMunicipio_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByMunicipio'
type MockDestinoStore_ListByMunicipio_Call struct {
	*mock.Call
}

// ListByMunicipio is a helper method to define mock.On call
//   - ctx context.Context
//   - municipioID int64
func (_e *MockDestinoStore_Expecter) ListByMunicipio(ctx interface{}, municipioID interface{}) *MockDestinoStore_ListByMunicipio_Call {
	return &MockDestinoStore_ListByMunicipio_Call{Call: _e.mock.On("ListByMunicipio", ctx, municipioID)}
}

func (_c *MockDestinoStore_ListByMunicipio_Call) Run(run func(ctx context.Context, municipioID int64)) *MockDestinoStore_ListByMunicipio_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDestinoStore_ListByMunicipio_Call) Return(destinos1 []destinos.Destino, err error) *MockDestinoStore_ListByMunicipio_Call {
	_c.Call.Return(destinos1, err)
	return _c
}

func (_c *MockDestinoStore_ListByMunicipio_Call) RunAndReturn(run func(ctx context.Context, municipioID int64) ([]destinos.Destino, error)) *MockDestinoStore_ListByMunicipio_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockDestinoStore
func (_mock *MockDestinoStore) Update(ctx context.Context, id int64, updateFunc func(*destinos.Destino) (bool, error)) (*destinos.Destino, error) {
	ret := _mock.Called(ctx, id, updateFunc)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *destinos.Destino
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, func(*destinos.Destino) (bool, error)) (*destinos.Destino, error)); ok {
		return returnFunc(ctx, id, updateFunc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, func(*destinos.Destino) (bool, error)) *destinos.Destino); ok {
		r0 = returnFunc(ctx, id, updateFunc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*destinos.Destino)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, func(*destinos.Destino) (bool, error)) error); ok {
		r1 = returnFunc(ctx, id, updateFunc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDestinoStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockDestinoStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - updateFunc func(*destinos.Destino) (bool, error)
func (_e *MockDestinoStore_Expecter) Update(ctx interface{}, id interface{}, updateFunc interface{}) *MockDestinoStore_Update_Call {
	return &MockDestinoStore_Update_Call{Call: _e.mock.On("Update", ctx, id, updateFunc)}
}

func (_c *MockDestinoStore_Update_Call) Run(run func(ctx context.Context, id int64, updateFunc func(*destinos.Destino) (bool, error))) *MockDestinoStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 func(*destinos.Destino) (bool, error)
		if args[2] != nil {
			arg2 = args[2].(func(*destinos.Destino) (bool, error))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDestinoStore_Update_Call) Return(destino *destinos.Destino, err error) *MockDestinoStore_Update_Call {
	_c.Call.Return(destino, err)
	return _c
}

func (_c *MockDestinoStore_Update_Call) RunAndReturn(run func(ctx context.Context, id int64, updateFunc func(*destinos.Destino) (bool, error)) (*destinos.Destino, error)) *MockDestinoStore_Update_Call {
	_c.Call.Return(run)
	return _c
}
