// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fredsaggio/bondrota-api/internal/motoristas"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMotoristaStore creates a new instance of MockMotoristaStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMotoristaStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMotoristaStore {
	mock := &MockMotoristaStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMotoristaStore is an autogenerated mock type for the MotoristaStore type
type MockMotoristaStore struct {
	mock.Mock
}

type MockMotoristaStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMotoristaStore) EXPECT() *MockMotoristaStore_Expecter {
	return &MockMotoristaStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockMotoristaStore
func (_mock *MockMotoristaStore) Create(ctx context.Context, input motoristas.MotoristaInput) (*motoristas.Motorista, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *motoristas.Motorista
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, motoristas.MotoristaInput) (*motoristas.Motorista, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, motoristas.MotoristaInput) *motoristas.Motorista); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*motoristas.Motorista)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, motoristas.MotoristaInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMotoristaStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMotoristaStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input motoristas.MotoristaInput
func (_e *MockMotoristaStore_Expecter) Create(ctx interface{}, input interface{}) *MockMotoristaStore_Create_Call {
	return &MockMotoristaStore_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockMotoristaStore_Create_Call) Run(run func(ctx context.Context, input motoristas.MotoristaInput)) *MockMotoristaStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 motoristas.MotoristaInput
		if args[1] != nil {
			arg1 = args[1].(motoristas.MotoristaInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMotoristaStore_Create_Call) Return(motorista *motoristas.Motorista, err error) *MockMotoristaStore_Create_Call {
	_c.Call.Return(motorista, err)
	return _c
}

func (_c *MockMotoristaStore_Create_Call) RunAndReturn(run func(ctx context.Context, input motoristas.MotoristaInput) (*motoristas.Motorista, error)) *MockMotoristaStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockMotoristaStore
func (_mock *MockMotoristaStore) Delete(ctx context.Context, motoristaID int64) error {
	ret := _mock.Called(ctx, motoristaID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, motoristaID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMotoristaStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMotoristaStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - motoristaID int64
func (_e *MockMotoristaStore_Expecter) Delete(ctx interface{}, motoristaID interface{}) *MockMotoristaStore_Delete_Call {
	return &MockMotoristaStore_Delete_Call{Call: _e.mock.On("Delete", ctx, motoristaID)}
}

func (_c *MockMotoristaStore_Delete_Call) Run(run func(ctx context.Context, motoristaID int64)) *MockMotoristaStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMotoristaStore_Delete_Call) Return(err error) *MockMotoristaStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMotoristaStore_Delete_Call) RunAndReturn(run func(ctx context.Context, motoristaID int64) error) *MockMotoristaStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCPF provides a mock function for the type MockMotoristaStore
func (_mock *MockMotoristaStore) GetByCPF(ctx context.Context, cpf string) (*motoristas.Motorista, error) {
	ret := _mock.Called(ctx, cpf)

	if len(ret) == 0 {
		panic("no return value specified for GetByCPF")
	}

	var r0 *motoristas.Motorista
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*motoristas.Motorista, error)); ok {
		return returnFunc(ctx, cpf)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *motoristas.Motorista); ok {
		r0 = returnFunc(ctx, cpf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*motoristas.Motorista)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, cpf)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMotoristaStore_GetByCPF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCPF'
type MockMotoristaStore_GetByCPF_Call struct {
	*mock.Call
}

// GetByCPF is a helper method to define mock.On call
//   - ctx context.Context
//   - cpf string
func (_e *MockMotoristaStore_Expecter) GetByCPF(ctx interface{}, cpf interface{}) *MockMotoristaStore_GetByCPF_Call {
	return &MockMotoristaStore_GetByCPF_Call{Call: _e.mock.On("GetByCPF", ctx, cpf)}
}

func (_c *MockMotoristaStore_GetByCPF_Call) Run(run func(ctx context.Context, cpf string)) *MockMotoristaStore_GetByCPF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMotoristaStore_GetByCPF_Call) Return(motorista *motoristas.Motorista, err error) *MockMotoristaStore_GetByCPF_Call {
	_c.Call.Return(motorista, err)
	return _c
}

func (_c *MockMotoristaStore_GetByCPF_Call) RunAndReturn(run func(ctx context.Context, cpf string) (*motoristas.Motorista, error)) *MockMotoristaStore_GetByCPF_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockMotoristaStore
func (_mock *MockMotoristaStore) GetByID(ctx context.Context, motoristaID int64) (*motoristas.Motorista, error) {
	ret := _mock.Called(ctx, motoristaID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *motoristas.Motorista
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*motoristas.Motorista, error)); ok {
		return returnFunc(ctx, motoristaID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *motoristas.Motorista); ok {
		r0 = returnFunc(ctx, motoristaID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*motoristas.Motorista)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, motoristaID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMotoristaStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockMotoristaStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - motoristaID int64
func (_e *MockMotoristaStore_Expecter) GetByID(ctx interface{}, motoristaID interface{}) *MockMotoristaStore_GetByID_Call {
	return &MockMotoristaStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, motoristaID)}
}

func (_c *MockMotoristaStore_GetByID_Call) Run(run func(ctx context.Context, motoristaID int64)) *MockMotoristaStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMotoristaStore_GetByID_Call) Return(motorista *motoristas.Motorista, err error) *MockMotoristaStore_GetByID_Call {
	_c.Call.Return(motorista, err)
	return _c
}

func (_c *MockMotoristaStore_GetByID_Call) RunAndReturn(run func(ctx context.Context, motoristaID int64) (*motoristas.Motorista, error)) *MockMotoristaStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockMotoristaStore
func (_mock *MockMotoristaStore) List(ctx context.Context) ([]motoristas.Motorista, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []motoristas.Motorista
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]motoristas.Motorista, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []motoristas.Motorista); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]motoristas.Motorista)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMotoristaStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockMotoristaStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMotoristaStore_Expecter) List(ctx interface{}) *MockMotoristaStore_List_Call {
	return &MockMotoristaStore_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockMotoristaStore_List_Call) Run(run func(ctx context.Context)) *MockMotoristaStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMotoristaStore_List_Call) Return(motoristas1 []motoristas.Motorista, err error) *MockMotoristaStore_List_Call {
	_c.Call.Return(motoristas1, err)
	return _c
}

func (_c *MockMotoristaStore_List_Call) RunAndReturn(run func(ctx context.Context) ([]motoristas.Motorista, error)) *MockMotoristaStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockMotoristaStore
func (_mock *MockMotoristaStore) Update(ctx context.Context, motoristaID int64, updateFunc func(*motoristas.Motorista) (bool, error)) (*motoristas.Motorista, error) {
	ret := _mock.Called(ctx, motoristaID, updateFunc)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *motoristas.Motorista
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, func(*motoristas.Motorista) (bool, error)) (*motoristas.Motorista, error)); ok {
		return returnFunc(ctx, motoristaID, updateFunc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, func(*motoristas.Motorista) (bool, error)) *motoristas.Motorista); ok {
		r0 = returnFunc(ctx, motoristaID, updateFunc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*motoristas.Motorista)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, func(*motoristas.Motorista) (bool, error)) error); ok {
		r1 = returnFunc(ctx, motoristaID, updateFunc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMotoristaStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMotoristaStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - motoristaID int64
//   - updateFunc func(*motoristas.Motorista) (bool, error)
func (_e *MockMotoristaStore_Expecter) Update(ctx interface{}, motoristaID interface{}, updateFunc interface{}) *MockMotoristaStore_Update_Call {
	return &MockMotoristaStore_Update_Call{Call: _e.mock.On("Update", ctx, motoristaID, updateFunc)}
}

func (_c *MockMotoristaStore_Update_Call) Run(run func(ctx context.Context, motoristaID int64, updateFunc func(*motoristas.Motorista) (bool, error))) *MockMotoristaStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 func(*motoristas.Motorista) (bool, error)
		if args[2] != nil {
			arg2 = args[2].(func(*motoristas.Motorista) (bool, error))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMotoristaStore_Update_Call) Return(motorista *motoristas.Motorista, err error) *MockMotoristaStore_Update_Call {
	_c.Call.Return(motorista, err)
	return _c
}

func (_c *MockMotoristaStore_Update_Call) RunAndReturn(run func(ctx context.Context, motoristaID int64, updateFunc func(*motoristas.Motorista) (bool, error)) (*motoristas.Motorista, error)) *MockMotoristaStore_Update_Call {
	_c.Call.Return(run)
	return _c
}
