// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fredsaggio/bondrota-api/internal/paradas"
	mock "github.com/stretchr/testify/mock"
)

// NewMockParadaStore creates a new instance of MockParadaStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParadaStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParadaStore {
	mock := &MockParadaStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParadaStore is an autogenerated mock type for the ParadaStore type
type MockParadaStore struct {
	mock.Mock
}

type MockParadaStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParadaStore) EXPECT() *MockParadaStore_Expecter {
	return &MockParadaStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockParadaStore
func (_mock *MockParadaStore) Create(ctx context.Context, input paradas.ParadaInput) (*paradas.Parada, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *paradas.Parada
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, paradas.ParadaInput) (*paradas.Parada, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, paradas.ParadaInput) *paradas.Parada); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paradas.Parada)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, paradas.ParadaInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParadaStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockParadaStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input paradas.ParadaInput
func (_e *MockParadaStore_Expecter) Create(ctx interface{}, input interface{}) *MockParadaStore_Create_Call {
	return &MockParadaStore_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockParadaStore_Create_Call) Run(run func(ctx context.Context, input paradas.ParadaInput)) *MockParadaStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 paradas.ParadaInput
		if args[1] != nil {
			arg1 = args[1].(paradas.ParadaInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockParadaStore_Create_Call) Return(parada *paradas.Parada, err error) *MockParadaStore_Create_Call {
	_c.Call.Return(parada, err)
	return _c
}

func (_c *MockParadaStore_Create_Call) RunAndReturn(run func(ctx context.Context, input paradas.ParadaInput) (*paradas.Parada, error)) *MockParadaStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockParadaStore
func (_mock *MockParadaStore) Delete(ctx context.Context, paradaID int64) error {
	ret := _mock.Called(ctx, paradaID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, paradaID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockParadaStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockParadaStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - paradaID int64
func (_e *MockParadaStore_Expecter) Delete(ctx interface{}, paradaID interface{}) *MockParadaStore_Delete_Call {
	return &MockParadaStore_Delete_Call{Call: _e.mock.On("Delete", ctx, paradaID)}
}

func (_c *MockParadaStore_Delete_Call) Run(run func(ctx context.Context, paradaID int64)) *MockParadaStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockParadaStore_Delete_Call) Return(err error) *MockParadaStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockParadaStore_Delete_Call) RunAndReturn(run func(ctx context.Context, paradaID int64) error) *MockParadaStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockParadaStore
func (_mock *MockParadaStore) GetByID(ctx context.Context, paradaID int64) (*paradas.Parada, error) {
	ret := _mock.Called(ctx, paradaID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *paradas.Parada
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*paradas.Parada, error)); ok {
		return returnFunc(ctx, paradaID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *paradas.Parada); ok {
		r0 = returnFunc(ctx, paradaID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paradas.Parada)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, paradaID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParadaStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockParadaStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - paradaID int64
func (_e *MockParadaStore_Expecter) GetByID(ctx interface{}, paradaID interface{}) *MockParadaStore_GetByID_Call {
	return &MockParadaStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, paradaID)}
}

func (_c *MockParadaStore_GetByID_Call) Run(run func(ctx context.Context, paradaID int64)) *MockParadaStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockParadaStore_GetByID_Call) Return(parada *paradas.Parada, err error) *MockParadaStore_GetByID_Call {
	_c.Call.Return(parada, err)
	return _c
}

func (_c *MockParadaStore_GetByID_Call) RunAndReturn(run func(ctx context.Context, paradaID int64) (*paradas.Parada, error)) *MockParadaStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockParadaStore
func (_mock *MockParadaStore) List(ctx context.Context) ([]paradas.Parada, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []paradas.Parada
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]paradas.Parada, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []paradas.Parada); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]paradas.Parada)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParadaStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockParadaStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockParadaStore_Expecter) List(ctx interface{}) *MockParadaStore_List_Call {
	return &MockParadaStore_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockParadaStore_List_Call) Run(run func(ctx context.Context)) *MockParadaStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockParadaStore_List_Call) Return(paradas1 []paradas.Parada, err error) *MockParadaStore_List_Call {
	_c.Call.Return(paradas1, err)
	return _c
}

func (_c *MockParadaStore_List_Call) RunAndReturn(run func(ctx context.Context) ([]paradas.Parada, error)) *MockParadaStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCity provides a mock function for the type MockParadaStore
func (_mock *MockParadaStore) ListByCity(ctx context.Context, cidade string) ([]paradas.Parada, error) {
	ret := _mock.Called(ctx, cidade)

	if len(ret) == 0 {
		panic("no return value specified for ListByCity")
	}

	var r0 []paradas.Parada
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]paradas.Parada, error)); ok {
		return returnFunc(ctx, cidade)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []paradas.Parada); ok {
		r0 = returnFunc(ctx, cidade)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]paradas.Parada)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, cidade)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParadaStore_ListByCity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCity'
type MockParadaStore_ListByCity_Call struct {
	*mock.Call
}

// ListByCity is a helper method to define mock.On call
//   - ctx context.Context
//   - cidade string
func (_e *MockParadaStore_Expecter) ListByCity(ctx interface{}, cidade interface{}) *MockParadaStore_ListByCity_Call {
	return &MockParadaStore_ListByCity_Call{Call: _e.mock.On("ListByCity", ctx, cidade)}
}

func (_c *MockParadaStore_ListByCity_Call) Run(run func(ctx context.Context, cidade string)) *MockParadaStore_ListByCity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockParadaStore_ListByCity_Call) Return(paradas1 []paradas.Parada, err error) *MockParadaStore_ListByCity_Call {
	_c.Call.Return(paradas1, err)
	return _c
}

func (_c *MockParadaStore_ListByCity_Call) RunAndReturn(run func(ctx context.Context, cidade string) ([]paradas.Parada, error)) *MockParadaStore_ListByCity_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockParadaStore
func (_mock *MockParadaStore) Update(ctx context.Context, paradaID int64, updateFunc func(*paradas.Parada) (bool, error)) (*paradas.Parada, error) {
	ret := _mock.Called(ctx, paradaID, updateFunc)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *paradas.Parada
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, func(*paradas.Parada) (bool, error)) (*paradas.Parada, error)); ok {
		return returnFunc(ctx, paradaID, updateFunc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, func(*paradas.Parada) (bool, error)) *paradas.Parada); ok {
		r0 = returnFunc(ctx, paradaID, updateFunc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paradas.Parada)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, func(*paradas.Parada) (bool, error)) error); ok {
		r1 = returnFunc(ctx, paradaID, updateFunc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParadaStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockParadaStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - paradaID int64
//   - updateFunc func(*paradas.Parada) (bool, error)
func (_e *MockParadaStore_Expecter) Update(ctx interface{}, paradaID interface{}, updateFunc interface{}) *MockParadaStore_Update_Call {
	return &MockParadaStore_Update_Call{Call: _e.mock.On("Update", ctx, paradaID, updateFunc)}
}

func (_c *MockParadaStore_Update_Call) Run(run func(ctx context.Context, paradaID int64, updateFunc func(*paradas.Parada) (bool, error))) *MockParadaStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 func(*paradas.Parada) (bool, error)
		if args[2] != nil {
			arg2 = args[2].(func(*paradas.Parada) (bool, error))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockParadaStore_Update_Call) Return(parada *paradas.Parada, err error) *MockParadaStore_Update_Call {
	_c.Call.Return(parada, err)
	return _c
}

func (_c *MockParadaStore_Update_Call) RunAndReturn(run func(ctx context.Context, paradaID int64, updateFunc func(*paradas.Parada) (bool, error)) (*paradas.Parada, error)) *MockParadaStore_Update_Call {
	_c.Call.Return(run)
	return _c
}
