// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fredsaggio/bondrota-api/internal/reservas"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReservaStore creates a new instance of MockReservaStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReservaStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReservaStore {
	mock := &MockReservaStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReservaStore is an autogenerated mock type for the ReservaStore type
type MockReservaStore struct {
	mock.Mock
}

type MockReservaStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReservaStore) EXPECT() *MockReservaStore_Expecter {
	return &MockReservaStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockReservaStore
func (_mock *MockReservaStore) Create(ctx context.Context, input reservas.ReservaInput) (*reservas.Reserva, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *reservas.Reserva
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, reservas.ReservaInput) (*reservas.Reserva, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, reservas.ReservaInput) *reservas.Reserva); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reservas.Reserva)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, reservas.ReservaInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservaStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockReservaStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input reservas.ReservaInput
func (_e *MockReservaStore_Expecter) Create(ctx interface{}, input interface{}) *MockReservaStore_Create_Call {
	return &MockReservaStore_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockReservaStore_Create_Call) Run(run func(ctx context.Context, input reservas.ReservaInput)) *MockReservaStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 reservas.ReservaInput
		if args[1] != nil {
			arg1 = args[1].(reservas.ReservaInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReservaStore_Create_Call) Return(reserva *reservas.Reserva, err error) *MockReservaStore_Create_Call {
	_c.Call.Return(reserva, err)
	return _c
}

func (_c *MockReservaStore_Create_Call) RunAndReturn(run func(ctx context.Context, input reservas.ReservaInput) (*reservas.Reserva, error)) *MockReservaStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockReservaStore
func (_mock *MockReservaStore) Delete(ctx context.Context, reservaID int64) error {
	ret := _mock.Called(ctx, reservaID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, reservaID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReservaStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockReservaStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - reservaID int64
func (_e *MockReservaStore_Expecter) Delete(ctx interface{}, reservaID interface{}) *MockReservaStore_Delete_Call {
	return &MockReservaStore_Delete_Call{Call: _e.mock.On("Delete", ctx, reservaID)}
}

func (_c *MockReservaStore_Delete_Call) Run(run func(ctx context.Context, reservaID int64)) *MockReservaStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReservaStore_Delete_Call) Return(err error) *MockReservaStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReservaStore_Delete_Call) RunAndReturn(run func(ctx context.Context, reservaID int64) error) *MockReservaStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockReservaStore
func (_mock *MockReservaStore) GetByID(ctx context.Context, reservaID int64) (*reservas.Reserva, error) {
	ret := _mock.Called(ctx, reservaID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *reservas.Reserva
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*reservas.Reserva, error)); ok {
		return returnFunc(ctx, reservaID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *reservas.Reserva); ok {
		r0 = returnFunc(ctx, reservaID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reservas.Reserva)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, reservaID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservaStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockReservaStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - reservaID int64
func (_e *MockReservaStore_Expecter) GetByID(ctx interface{}, reservaID interface{}) *MockReservaStore_GetByID_Call {
	return &MockReservaStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, reservaID)}
}

func (_c *MockReservaStore_GetByID_Call) Run(run func(ctx context.Context, reservaID int64)) *MockReservaStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReservaStore_GetByID_Call) Return(reserva *reservas.Reserva, err error) *MockReservaStore_GetByID_Call {
	_c.Call.Return(reserva, err)
	return _c
}

func (_c *MockReservaStore_GetByID_Call) RunAndReturn(run func(ctx context.Context, reservaID int64) (*reservas.Reserva, error)) *MockReservaStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetVinculoSnapshot provides a mock function for the type MockReservaStore
func (_mock *MockReservaStore) GetVinculoSnapshot(ctx context.Context, vinculoID int64) (reservas.VinculoSnapshot, error) {
	ret := _mock.Called(ctx, vinculoID)

	if len(ret) == 0 {
		panic("no return value specified for GetVinculoSnapshot")
	}

	var r0 reservas.VinculoSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (reservas.VinculoSnapshot, error)); ok {
		return returnFunc(ctx, vinculoID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) reservas.VinculoSnapshot); ok {
		r0 = returnFunc(ctx, vinculoID)
	} else {
		r0 = ret.Get(0).(reservas.VinculoSnapshot)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, vinculoID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservaStore_GetVinculoSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVinculoSnapshot'
type MockReservaStore_GetVinculoSnapshot_Call struct {
	*mock.Call
}

// GetVinculoSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - vinculoID int64
func (_e *MockReservaStore_Expecter) GetVinculoSnapshot(ctx interface{}, vinculoID interface{}) *MockReservaStore_GetVinculoSnapshot_Call {
	return &MockReservaStore_GetVinculoSnapshot_Call{Call: _e.mock.On("GetVinculoSnapshot", ctx, vinculoID)}
}

func (_c *MockReservaStore_GetVinculoSnapshot_Call) Run(run func(ctx context.Context, vinculoID int64)) *MockReservaStore_GetVinculoSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReservaStore_GetVinculoSnapshot_Call) Return(vinculoSnapshot reservas.VinculoSnapshot, err error) *MockReservaStore_GetVinculoSnapshot_Call {
	_c.Call.Return(vinculoSnapshot, err)
	return _c
}

func (_c *MockReservaStore_GetVinculoSnapshot_Call) RunAndReturn(run func(ctx context.Context, vinculoID int64) (reservas.VinculoSnapshot, error)) *MockReservaStore_GetVinculoSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockReservaStore
func (_mock *MockReservaStore) List(ctx context.Context) ([]reservas.Reserva, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []reservas.Reserva
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]reservas.Reserva, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []reservas.Reserva); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reservas.Reserva)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservaStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockReservaStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReservaStore_Expecter) List(ctx interface{}) *MockReservaStore_List_Call {
	return &MockReservaStore_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockReservaStore_List_Call) Run(run func(ctx context.Context)) *MockReservaStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReservaStore_List_Call) Return(reservas1 []reservas.Reserva, err error) *MockReservaStore_List_Call {
	_c.Call.Return(reservas1, err)
	return _c
}

func (_c *MockReservaStore_List_Call) RunAndReturn(run func(ctx context.Context) ([]reservas.Reserva, error)) *MockReservaStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCliente provides a mock function for the type MockReservaStore
func (_mock *MockReservaStore) ListByCliente(ctx context.Context, clienteID int64) ([]reservas.Reserva, error) {
	ret := _mock.Called(ctx, clienteID)

	if len(ret) == 0 {
		panic("no return value specified for ListByCliente")
	}

	var r0 []reservas.Reserva
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]reservas.Reserva, error)); ok {
		return returnFunc(ctx, clienteID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []reservas.Reserva); ok {
		r0 = returnFunc(ctx, clienteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reservas.Reserva)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, clienteID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservaStore_ListByCliente_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCliente'
type MockReservaStore_ListByCliente_Call struct {
	*mock.Call
}

// ListByCliente is a helper method to define mock.On call
//   - ctx context.Context
//   - clienteID int64
func (_e *MockReservaStore_Expecter) ListByCliente(ctx interface{}, clienteID interface{}) *MockReservaStore_ListByCliente_Call {
	return &MockReservaStore_ListByCliente_Call{Call: _e.mock.On("ListByCliente", ctx, clienteID)}
}

func (_c *MockReservaStore_ListByCliente_Call) Run(run func(ctx context.Context, clienteID int64)) *MockReservaStore_ListByCliente_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReservaStore_ListByCliente_Call) Return(reservas1 []reservas.Reserva, err error) *MockReservaStore_ListByCliente_Call {
	_c.Call.Return(reservas1, err)
	return _c
}

func (_c *MockReservaStore_ListByCliente_Call) RunAndReturn(run func(ctx context.Context, clienteID int64) ([]reservas.Reserva, error)) *MockReservaStore_ListByCliente_Call {
	_c.Call.Return(run)
	return _c
}

// ListByVinculo provides a mock function for the type MockReservaStore
func (_mock *MockReservaStore) ListByVinculo(ctx context.Context, clienteID int64, vinculoID int64) ([]reservas.Reserva, error) {
	ret := _mock.Called(ctx, clienteID, vinculoID)

	if len(ret) == 0 {
		panic("no return value specified for ListByVinculo")
	}

	var r0 []reservas.Reserva
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) ([]reservas.Reserva, error)); ok {
		return returnFunc(ctx, clienteID, vinculoID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) []reservas.Reserva); ok {
		r0 = returnFunc(ctx, clienteID, vinculoID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]reservas.Reserva)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, clienteID, vinculoID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservaStore_ListByVinculo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByVinculo'
type MockReservaStore_ListByVinculo_Call struct {
	*mock.Call
}

// ListByVinculo is a helper method to define mock.On call
//   - ctx context.Context
//   - clienteID int64
//   - vinculoID int64
func (_e *MockReservaStore_Expecter) ListByVinculo(ctx interface{}, clienteID interface{}, vinculoID interface{}) *MockReservaStore_ListByVinculo_Call {
	return &MockReservaStore_ListByVinculo_Call{Call: _e.mock.On("ListByVinculo", ctx, clienteID, vinculoID)}
}

func (_c *MockReservaStore_ListByVinculo_Call) Run(run func(ctx context.Context, clienteID int64, vinculoID int64)) *MockReservaStore_ListByVinculo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReservaStore_ListByVinculo_Call) Return(reservas1 []reservas.Reserva, err error) *MockReservaStore_ListByVinculo_Call {
	_c.Call.Return(reservas1, err)
	return _c
}

func (_c *MockReservaStore_ListByVinculo_Call) RunAndReturn(run func(ctx context.Context, clienteID int64, vinculoID int64) ([]reservas.Reserva, error)) *MockReservaStore_ListByVinculo_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockReservaStore
func (_mock *MockReservaStore) Update(ctx context.Context, reservaID int64, updateFunc func(*reservas.Reserva) (bool, error)) (*reservas.Reserva, error) {
	ret := _mock.Called(ctx, reservaID, updateFunc)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *reservas.Reserva
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, func(*reservas.Reserva) (bool, error)) (*reservas.Reserva, error)); ok {
		return returnFunc(ctx, reservaID, updateFunc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, func(*reservas.Reserva) (bool, error)) *reservas.Reserva); ok {
		r0 = returnFunc(ctx, reservaID, updateFunc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reservas.Reserva)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, func(*reservas.Reserva) (bool, error)) error); ok {
		r1 = returnFunc(ctx, reservaID, updateFunc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReservaStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockReservaStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - reservaID int64
//   - updateFunc func(*reservas.Reserva) (bool, error)
func (_e *MockReservaStore_Expecter) Update(ctx interface{}, reservaID interface{}, updateFunc interface{}) *MockReservaStore_Update_Call {
	return &MockReservaStore_Update_Call{Call: _e.mock.On("Update", ctx, reservaID, updateFunc)}
}

func (_c *MockReservaStore_Update_Call) Run(run func(ctx context.Context, reservaID int64, updateFunc func(*reservas.Reserva) (bool, error))) *MockReservaStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 func(*reservas.Reserva) (bool, error)
		if args[2] != nil {
			arg2 = args[2].(func(*reservas.Reserva) (bool, error))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReservaStore_Update_Call) Return(reserva *reservas.Reserva, err error) *MockReservaStore_Update_Call {
	_c.Call.Return(reserva, err)
	return _c
}

func (_c *MockReservaStore_Update_Call) RunAndReturn(run func(ctx context.Context, reservaID int64, updateFunc func(*reservas.Reserva) (bool, error)) (*reservas.Reserva, error)) *MockReservaStore_Update_Call {
	_c.Call.Return(run)
	return _c
}
