// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/fredsaggio/bondrota-api/internal/retencao"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// RemoverCiclosAntigos provides a mock function for the type MockStore
func (_mock *MockStore) RemoverCiclosAntigos(ctx context.Context, corte time.Time, limite int) (int64, error) {
	ret := _mock.Called(ctx, corte, limite)

	if len(ret) == 0 {
		panic("no return value specified for RemoverCiclosAntigos")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) (int64, error)); ok {
		return returnFunc(ctx, corte, limite)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) int64); ok {
		r0 = returnFunc(ctx, corte, limite)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = returnFunc(ctx, corte, limite)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_RemoverCiclosAntigos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoverCiclosAntigos'
type MockStore_RemoverCiclosAntigos_Call struct {
	*mock.Call
}

// RemoverCiclosAntigos is a helper method to define mock.On call
//   - ctx context.Context
//   - corte time.Time
//   - limite int
func (_e *MockStore_Expecter) RemoverCiclosAntigos(ctx interface{}, corte interface{}, limite interface{}) *MockStore_RemoverCiclosAntigos_Call {
	return &MockStore_RemoverCiclosAntigos_Call{Call: _e.mock.On("RemoverCiclosAntigos", ctx, corte, limite)}
}

func (_c *MockStore_RemoverCiclosAntigos_Call) Run(run func(ctx context.Context, corte time.Time, limite int)) *MockStore_RemoverCiclosAntigos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_RemoverCiclosAntigos_Call) Return(n int64, err error) *MockStore_RemoverCiclosAntigos_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStore_RemoverCiclosAntigos_Call) RunAndReturn(run func(ctx context.Context, corte time.Time, limite int) (int64, error)) *MockStore_RemoverCiclosAntigos_Call {
	_c.Call.Return(run)
	return _c
}

// RemoverExecucoesAntigas provides a mock function for the type MockStore
func (_mock *MockStore) RemoverExecucoesAntigas(ctx context.Context, corte time.Time, limite int) (int64, error) {
	ret := _mock.Called(ctx, corte, limite)

	if len(ret) == 0 {
		panic("no return value specified for RemoverExecucoesAntigas")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) (int64, error)); ok {
		return returnFunc(ctx, corte, limite)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) int64); ok {
		r0 = returnFunc(ctx, corte, limite)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = returnFunc(ctx, corte, limite)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_RemoverExecucoesAntigas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoverExecucoesAntigas'
type MockStore_RemoverExecucoesAntigas_Call struct {
	*mock.Call
}

// RemoverExecucoesAntigas is a helper method to define mock.On call
//   - ctx context.Context
//   - corte time.Time
//   - limite int
func (_e *MockStore_Expecter) RemoverExecucoesAntigas(ctx interface{}, corte interface{}, limite interface{}) *MockStore_RemoverExecucoesAntigas_Call {
	return &MockStore_RemoverExecucoesAntigas_Call{Call: _e.mock.On("RemoverExecucoesAntigas", ctx, corte, limite)}
}

func (_c *MockStore_RemoverExecucoesAntigas_Call) Run(run func(ctx context.Context, corte time.Time, limite int)) *MockStore_RemoverExecucoesAntigas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_RemoverExecucoesAntigas_Call) Return(n int64, err error) *MockStore_RemoverExecucoesAntigas_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStore_RemoverExecucoesAntigas_Call) RunAndReturn(run func(ctx context.Context, corte time.Time, limite int) (int64, error)) *MockStore_RemoverExecucoesAntigas_Call {
	_c.Call.Return(run)
	return _c
}

// RemoverReservasAntigas provides a mock function for the type MockStore
func (_mock *MockStore) RemoverReservasAntigas(ctx context.Context, corte time.Time, limite int) (int64, error) {
	ret := _mock.Called(ctx, corte, limite)

	if len(ret) == 0 {
		panic("no return value specified for RemoverReservasAntigas")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) (int64, error)); ok {
		return returnFunc(ctx, corte, limite)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, int) int64); ok {
		r0 = returnFunc(ctx, corte, limite)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time, int) error); ok {
		r1 = returnFunc(ctx, corte, limite)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_RemoverReservasAntigas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoverReservasAntigas'
type MockStore_RemoverReservasAntigas_Call struct {
	*mock.Call
}

// RemoverReservasAntigas is a helper method to define mock.On call
//   - ctx context.Context
//   - corte time.Time
//   - limite int
func (_e *MockStore_Expecter) RemoverReservasAntigas(ctx interface{}, corte interface{}, limite interface{}) *MockStore_RemoverReservasAntigas_Call {
	return &MockStore_RemoverReservasAntigas_Call{Call: _e.mock.On("RemoverReservasAntigas", ctx, corte, limite)}
}

func (_c *MockStore_RemoverReservasAntigas_Call) Run(run func(ctx context.Context, corte time.Time, limite int)) *MockStore_RemoverReservasAntigas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStore_RemoverReservasAntigas_Call) Return(n int64, err error) *MockStore_RemoverReservasAntigas_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockStore_RemoverReservasAntigas_Call) RunAndReturn(run func(ctx context.Context, corte time.Time, limite int) (int64, error)) *MockStore_RemoverReservasAntigas_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Limpar provides a mock function for the type MockService
func (_mock *MockService) Limpar(ctx context.Context) (retencao.ResumoLimpeza, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Limpar")
	}

	var r0 retencao.ResumoLimpeza
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (retencao.ResumoLimpeza, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) retencao.ResumoLimpeza); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(retencao.ResumoLimpeza)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Limpar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Limpar'
type MockService_Limpar_Call struct {
	*mock.Call
}

// Limpar is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) Limpar(ctx interface{}) *MockService_Limpar_Call {
	return &MockService_Limpar_Call{Call: _e.mock.On("Limpar", ctx)}
}

func (_c *MockService_Limpar_Call) Run(run func(ctx context.Context)) *MockService_Limpar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Limpar_Call) Return(resumoLimpeza retencao.ResumoLimpeza, err error) *MockService_Limpar_Call {
	_c.Call.Return(resumoLimpeza, err)
	return _c
}

func (_c *MockService_Limpar_Call) RunAndReturn(run func(ctx context.Context) (retencao.ResumoLimpeza, error)) *MockService_Limpar_Call {
	_c.Call.Return(run)
	return _c
}
