// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fredsaggio/bondrota-api/internal/rotasinternas"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRotaInternaStore creates a new instance of MockRotaInternaStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRotaInternaStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRotaInternaStore {
	mock := &MockRotaInternaStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRotaInternaStore is an autogenerated mock type for the RotaInternaStore type
type MockRotaInternaStore struct {
	mock.Mock
}

type MockRotaInternaStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRotaInternaStore) EXPECT() *MockRotaInternaStore_Expecter {
	return &MockRotaInternaStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRotaInternaStore
func (_mock *MockRotaInternaStore) Create(ctx context.Context, input rotasinternas.CreateRotaInternaInput) (*rotasinternas.RotaInterna, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *rotasinternas.RotaInterna
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, rotasinternas.CreateRotaInternaInput) (*rotasinternas.RotaInterna, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, rotasinternas.CreateRotaInternaInput) *rotasinternas.RotaInterna); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rotasinternas.RotaInterna)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, rotasinternas.CreateRotaInternaInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRotaInternaStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRotaInternaStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input rotasinternas.CreateRotaInternaInput
func (_e *MockRotaInternaStore_Expecter) Create(ctx interface{}, input interface{}) *MockRotaInternaStore_Create_Call {
	return &MockRotaInternaStore_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockRotaInternaStore_Create_Call) Run(run func(ctx context.Context, input rotasinternas.CreateRotaInternaInput)) *MockRotaInternaStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 rotasinternas.CreateRotaInternaInput
		if args[1] != nil {
			arg1 = args[1].(rotasinternas.CreateRotaInternaInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRotaInternaStore_Create_Call) Return(rotaInterna *rotasinternas.RotaInterna, err error) *MockRotaInternaStore_Create_Call {
	_c.Call.Return(rotaInterna, err)
	return _c
}

func (_c *MockRotaInternaStore_Create_Call) RunAndReturn(run func(ctx context.Context, input rotasinternas.CreateRotaInternaInput) (*rotasinternas.RotaInterna, error)) *MockRotaInternaStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRotaInternaStore
func (_mock *MockRotaInternaStore) Delete(ctx context.Context, rotaInternaID int64) error {
	ret := _mock.Called(ctx, rotaInternaID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, rotaInternaID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRotaInternaStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRotaInternaStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - rotaInternaID int64
func (_e *MockRotaInternaStore_Expecter) Delete(ctx interface{}, rotaInternaID interface{}) *MockRotaInternaStore_Delete_Call {
	return &MockRotaInternaStore_Delete_Call{Call: _e.mock.On("Delete", ctx, rotaInternaID)}
}

func (_c *MockRotaInternaStore_Delete_Call) Run(run func(ctx context.Context, rotaInternaID int64)) *MockRotaInternaStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRotaInternaStore_Delete_Call) Return(err error) *MockRotaInternaStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRotaInternaStore_Delete_Call) RunAndReturn(run func(ctx context.Context, rotaInternaID int64) error) *MockRotaInternaStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockRotaInternaStore
func (_mock *MockRotaInternaStore) GetByID(ctx context.Context, rotaInternaID int64) (*rotasinternas.RotaInterna, error) {
	ret := _mock.Called(ctx, rotaInternaID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *rotasinternas.RotaInterna
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*rotasinternas.RotaInterna, error)); ok {
		return returnFunc(ctx, rotaInternaID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *rotasinternas.RotaInterna); ok {
		r0 = returnFunc(ctx, rotaInternaID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rotasinternas.RotaInterna)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, rotaInternaID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRotaInternaStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRotaInternaStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - rotaInternaID int64
func (_e *MockRotaInternaStore_Expecter) GetByID(ctx interface{}, rotaInternaID interface{}) *MockRotaInternaStore_GetByID_Call {
	return &MockRotaInternaStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, rotaInternaID)}
}

func (_c *MockRotaInternaStore_GetByID_Call) Run(run func(ctx context.Context, rotaInternaID int64)) *MockRotaInternaStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRotaInternaStore_GetByID_Call) Return(rotaInterna *rotasinternas.RotaInterna, err error) *MockRotaInternaStore_GetByID_Call {
	_c.Call.Return(rotaInterna, err)
	return _c
}

func (_c *MockRotaInternaStore_GetByID_Call) RunAndReturn(run func(ctx context.Context, rotaInternaID int64) (*rotasinternas.RotaInterna, error)) *MockRotaInternaStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRotaInternaStore
func (_mock *MockRotaInternaStore) List(ctx context.Context) ([]rotasinternas.RotaInterna, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []rotasinternas.RotaInterna
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]rotasinternas.RotaInterna, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []rotasinternas.RotaInterna); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rotasinternas.RotaInterna)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRotaInternaStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRotaInternaStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRotaInternaStore_Expecter) List(ctx interface{}) *MockRotaInternaStore_List_Call {
	return &MockRotaInternaStore_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockRotaInternaStore_List_Call) Run(run func(ctx context.Context)) *MockRotaInternaStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRotaInternaStore_List_Call) Return(rotaInternas []rotasinternas.RotaInterna, err error) *MockRotaInternaStore_List_Call {
	_c.Call.Return(rotaInternas, err)
	return _c
}

func (_c *MockRotaInternaStore_List_Call) RunAndReturn(run func(ctx context.Context) ([]rotasinternas.RotaInterna, error)) *MockRotaInternaStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCity provides a mock function for the type MockRotaInternaStore
func (_mock *MockRotaInternaStore) ListByCity(ctx context.Context, cidade string) ([]rotasinternas.RotaInterna, error) {
	ret := _mock.Called(ctx, cidade)

	if len(ret) == 0 {
		panic("no return value specified for ListByCity")
	}

	var r0 []rotasinternas.RotaInterna
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]rotasinternas.RotaInterna, error)); ok {
		return returnFunc(ctx, cidade)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []rotasinternas.RotaInterna); ok {
		r0 = returnFunc(ctx, cidade)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rotasinternas.RotaInterna)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, cidade)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRotaInternaStore_ListByCity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCity'
type MockRotaInternaStore_ListByCity_Call struct {
	*mock.Call
}

// ListByCity is a helper method to define mock.On call
//   - ctx context.Context
//   - cidade string
func (_e *MockRotaInternaStore_Expecter) ListByCity(ctx interface{}, cidade interface{}) *MockRotaInternaStore_ListByCity_Call {
	return &MockRotaInternaStore_ListByCity_Call{Call: _e.mock.On("ListByCity", ctx, cidade)}
}

func (_c *MockRotaInternaStore_ListByCity_Call) Run(run func(ctx context.Context, cidade string)) *MockRotaInternaStore_ListByCity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRotaInternaStore_ListByCity_Call) Return(rotaInternas []rotasinternas.RotaInterna, err error) *MockRotaInternaStore_ListByCity_Call {
	_c.Call.Return(rotaInternas, err)
	return _c
}

func (_c *MockRotaInternaStore_ListByCity_Call) RunAndReturn(run func(ctx context.Context, cidade string) ([]rotasinternas.RotaInterna, error)) *MockRotaInternaStore_ListByCity_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateParadas provides a mock function for the type MockRotaInternaStore
func (_mock *MockRotaInternaStore) UpdateParadas(ctx context.Context, rotaInternaID int64, input rotasinternas.UpdateParadasInput) (*rotasinternas.RotaInterna, error) {
	ret := _mock.Called(ctx, rotaInternaID, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateParadas")
	}

	var r0 *rotasinternas.RotaInterna
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, rotasinternas.UpdateParadasInput) (*rotasinternas.RotaInterna, error)); ok {
		return returnFunc(ctx, rotaInternaID, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, rotasinternas.UpdateParadasInput) *rotasinternas.RotaInterna); ok {
		r0 = returnFunc(ctx, rotaInternaID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rotasinternas.RotaInterna)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, rotasinternas.UpdateParadasInput) error); ok {
		r1 = returnFunc(ctx, rotaInternaID, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRotaInternaStore_UpdateParadas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateParadas'
type MockRotaInternaStore_UpdateParadas_Call struct {
	*mock.Call
}

// UpdateParadas is a helper method to define mock.On call
//   - ctx context.Context
//   - rotaInternaID int64
//   - input rotasinternas.UpdateParadasInput
func (_e *MockRotaInternaStore_Expecter) UpdateParadas(ctx interface{}, rotaInternaID interface{}, input interface{}) *MockRotaInternaStore_UpdateParadas_Call {
	return &MockRotaInternaStore_UpdateParadas_Call{Call: _e.mock.On("UpdateParadas", ctx, rotaInternaID, input)}
}

func (_c *MockRotaInternaStore_UpdateParadas_Call) Run(run func(ctx context.Context, rotaInternaID int64, input rotasinternas.UpdateParadasInput)) *MockRotaInternaStore_UpdateParadas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 rotasinternas.UpdateParadasInput
		if args[2] != nil {
			arg2 = args[2].(rotasinternas.UpdateParadasInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRotaInternaStore_UpdateParadas_Call) Return(rotaInterna *rotasinternas.RotaInterna, err error) *MockRotaInternaStore_UpdateParadas_Call {
	_c.Call.Return(rotaInterna, err)
	return _c
}

func (_c *MockRotaInternaStore_UpdateParadas_Call) RunAndReturn(run func(ctx context.Context, rotaInternaID int64, input rotasinternas.UpdateParadasInput) (*rotasinternas.RotaInterna, error)) *MockRotaInternaStore_UpdateParadas_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRotaInternaService creates a new instance of MockRotaInternaService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRotaInternaService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRotaInternaService {
	mock := &MockRotaInternaService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRotaInternaService is an autogenerated mock type for the RotaInternaService type
type MockRotaInternaService struct {
	mock.Mock
}

type MockRotaInternaService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRotaInternaService) EXPECT() *MockRotaInternaService_Expecter {
	return &MockRotaInternaService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRotaInternaService
func (_mock *MockRotaInternaService) Create(ctx context.Context, input rotasinternas.CreateRotaInternaInput) (*rotasinternas.RotaInterna, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *rotasinternas.RotaInterna
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, rotasinternas.CreateRotaInternaInput) (*rotasinternas.RotaInterna, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, rotasinternas.CreateRotaInternaInput) *rotasinternas.RotaInterna); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rotasinternas.RotaInterna)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, rotasinternas.CreateRotaInternaInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRotaInternaService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRotaInternaService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input rotasinternas.CreateRotaInternaInput
func (_e *MockRotaInternaService_Expecter) Create(ctx interface{}, input interface{}) *MockRotaInternaService_Create_Call {
	return &MockRotaInternaService_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockRotaInternaService_Create_Call) Run(run func(ctx context.Context, input rotasinternas.CreateRotaInternaInput)) *MockRotaInternaService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 rotasinternas.CreateRotaInternaInput
		if args[1] != nil {
			arg1 = args[1].(rotasinternas.CreateRotaInternaInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRotaInternaService_Create_Call) Return(rotaInterna *rotasinternas.RotaInterna, err error) *MockRotaInternaService_Create_Call {
	_c.Call.Return(rotaInterna, err)
	return _c
}

func (_c *MockRotaInternaService_Create_Call) RunAndReturn(run func(ctx context.Context, input rotasinternas.CreateRotaInternaInput) (*rotasinternas.RotaInterna, error)) *MockRotaInternaService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRotaInternaService
func (_mock *MockRotaInternaService) Delete(ctx context.Context, rotaInternaID int64) error {
	ret := _mock.Called(ctx, rotaInternaID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, rotaInternaID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRotaInternaService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRotaInternaService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - rotaInternaID int64
func (_e *MockRotaInternaService_Expecter) Delete(ctx interface{}, rotaInternaID interface{}) *MockRotaInternaService_Delete_Call {
	return &MockRotaInternaService_Delete_Call{Call: _e.mock.On("Delete", ctx, rotaInternaID)}
}

func (_c *MockRotaInternaService_Delete_Call) Run(run func(ctx context.Context, rotaInternaID int64)) *MockRotaInternaService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRotaInternaService_Delete_Call) Return(err error) *MockRotaInternaService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRotaInternaService_Delete_Call) RunAndReturn(run func(ctx context.Context, rotaInternaID int64) error) *MockRotaInternaService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockRotaInternaService
func (_mock *MockRotaInternaService) GetByID(ctx context.Context, rotaInternaID int64) (*rotasinternas.RotaInterna, error) {
	ret := _mock.Called(ctx, rotaInternaID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *rotasinternas.RotaInterna
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*rotasinternas.RotaInterna, error)); ok {
		return returnFunc(ctx, rotaInternaID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *rotasinternas.RotaInterna); ok {
		r0 = returnFunc(ctx, rotaInternaID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rotasinternas.RotaInterna)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, rotaInternaID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRotaInternaService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRotaInternaService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - rotaInternaID int64
func (_e *MockRotaInternaService_Expecter) GetByID(ctx interface{}, rotaInternaID interface{}) *MockRotaInternaService_GetByID_Call {
	return &MockRotaInternaService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, rotaInternaID)}
}

func (_c *MockRotaInternaService_GetByID_Call) Run(run func(ctx context.Context, rotaInternaID int64)) *MockRotaInternaService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRotaInternaService_GetByID_Call) Return(rotaInterna *rotasinternas.RotaInterna, err error) *MockRotaInternaService_GetByID_Call {
	_c.Call.Return(rotaInterna, err)
	return _c
}

func (_c *MockRotaInternaService_GetByID_Call) RunAndReturn(run func(ctx context.Context, rotaInternaID int64) (*rotasinternas.RotaInterna, error)) *MockRotaInternaService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRotaInternaService
func (_mock *MockRotaInternaService) List(ctx context.Context) ([]rotasinternas.RotaInterna, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []rotasinternas.RotaInterna
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]rotasinternas.RotaInterna, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []rotasinternas.RotaInterna); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rotasinternas.RotaInterna)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRotaInternaService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRotaInternaService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRotaInternaService_Expecter) List(ctx interface{}) *MockRotaInternaService_List_Call {
	return &MockRotaInternaService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockRotaInternaService_List_Call) Run(run func(ctx context.Context)) *MockRotaInternaService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRotaInternaService_List_Call) Return(rotaInternas []rotasinternas.RotaInterna, err error) *MockRotaInternaService_List_Call {
	_c.Call.Return(rotaInternas, err)
	return _c
}

func (_c *MockRotaInternaService_List_Call) RunAndReturn(run func(ctx context.Context) ([]rotasinternas.RotaInterna, error)) *MockRotaInternaService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByCity provides a mock function for the type MockRotaInternaService
func (_mock *MockRotaInternaService) ListByCity(ctx context.Context, cidade string) ([]rotasinternas.RotaInterna, error) {
	ret := _mock.Called(ctx, cidade)

	if len(ret) == 0 {
		panic("no return value specified for ListByCity")
	}

	var r0 []rotasinternas.RotaInterna
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]rotasinternas.RotaInterna, error)); ok {
		return returnFunc(ctx, cidade)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []rotasinternas.RotaInterna); ok {
		r0 = returnFunc(ctx, cidade)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rotasinternas.RotaInterna)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, cidade)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRotaInternaService_ListByCity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCity'
type MockRotaInternaService_ListByCity_Call struct {
	*mock.Call
}

// ListByCity is a helper method to define mock.On call
//   - ctx context.Context
//   - cidade string
func (_e *MockRotaInternaService_Expecter) ListByCity(ctx interface{}, cidade interface{}) *MockRotaInternaService_ListByCity_Call {
	return &MockRotaInternaService_ListByCity_Call{Call: _e.mock.On("ListByCity", ctx, cidade)}
}

func (_c *MockRotaInternaService_ListByCity_Call) Run(run func(ctx context.Context, cidade string)) *MockRotaInternaService_ListByCity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRotaInternaService_ListByCity_Call) Return(rotaInternas []rotasinternas.RotaInterna, err error) *MockRotaInternaService_ListByCity_Call {
	_c.Call.Return(rotaInternas, err)
	return _c
}

func (_c *MockRotaInternaService_ListByCity_Call) RunAndReturn(run func(ctx context.Context, cidade string) ([]rotasinternas.RotaInterna, error)) *MockRotaInternaService_ListByCity_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateParadas provides a mock function for the type MockRotaInternaService
func (_mock *MockRotaInternaService) UpdateParadas(ctx context.Context, rotaInternaID int64, input rotasinternas.UpdateParadasInput) (*rotasinternas.RotaInterna, error) {
	ret := _mock.Called(ctx, rotaInternaID, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateParadas")
	}

	var r0 *rotasinternas.RotaInterna
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, rotasinternas.UpdateParadasInput) (*rotasinternas.RotaInterna, error)); ok {
		return returnFunc(ctx, rotaInternaID, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, rotasinternas.UpdateParadasInput) *rotasinternas.RotaInterna); ok {
		r0 = returnFunc(ctx, rotaInternaID, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rotasinternas.RotaInterna)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, rotasinternas.UpdateParadasInput) error); ok {
		r1 = returnFunc(ctx, rotaInternaID, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRotaInternaService_UpdateParadas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateParadas'
type MockRotaInternaService_UpdateParadas_Call struct {
	*mock.Call
}

// UpdateParadas is a helper method to define mock.On call
//   - ctx context.Context
//   - rotaInternaID int64
//   - input rotasinternas.UpdateParadasInput
func (_e *MockRotaInternaService_Expecter) UpdateParadas(ctx interface{}, rotaInternaID interface{}, input interface{}) *MockRotaInternaService_UpdateParadas_Call {
	return &MockRotaInternaService_UpdateParadas_Call{Call: _e.mock.On("UpdateParadas", ctx, rotaInternaID, input)}
}

func (_c *MockRotaInternaService_UpdateParadas_Call) Run(run func(ctx context.Context, rotaInternaID int64, input rotasinternas.UpdateParadasInput)) *MockRotaInternaService_UpdateParadas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 rotasinternas.UpdateParadasInput
		if args[2] != nil {
			arg2 = args[2].(rotasinternas.UpdateParadasInput)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRotaInternaService_UpdateParadas_Call) Return(rotaInterna *rotasinternas.RotaInterna, err error) *MockRotaInternaService_UpdateParadas_Call {
	_c.Call.Return(rotaInterna, err)
	return _c
}

func (_c *MockRotaInternaService_UpdateParadas_Call) RunAndReturn(run func(ctx context.Context, rotaInternaID int64, input rotasinternas.UpdateParadasInput) (*rotasinternas.RotaInterna, error)) *MockRotaInternaService_UpdateParadas_Call {
	_c.Call.Return(run)
	return _c
}
