// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/fredsaggio/bondrota-api/internal/rotasdinamicas"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRotaDinamicaStore creates a new instance of MockRotaDinamicaStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRotaDinamicaStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRotaDinamicaStore {
	mock := &MockRotaDinamicaStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRotaDinamicaStore is an autogenerated mock type for the RotaDinamicaStore type
type MockRotaDinamicaStore struct {
	mock.Mock
}

type MockRotaDinamicaStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRotaDinamicaStore) EXPECT() *MockRotaDinamicaStore_Expecter {
	return &MockRotaDinamicaStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRotaDinamicaStore
func (_mock *MockRotaDinamicaStore) Create(ctx context.Context, input rotasdinamicas.RotaDinamicaInput) (*rotasdinamicas.RotaDinamicaComDestinos, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *rotasdinamicas.RotaDinamicaComDestinos
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, rotasdinamicas.RotaDinamicaInput) (*rotasdinamicas.RotaDinamicaComDestinos, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, rotasdinamicas.RotaDinamicaInput) *rotasdinamicas.RotaDinamicaComDestinos); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rotasdinamicas.RotaDinamicaComDestinos)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, rotasdinamicas.RotaDinamicaInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRotaDinamicaStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRotaDinamicaStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input rotasdinamicas.RotaDinamicaInput
func (_e *MockRotaDinamicaStore_Expecter) Create(ctx interface{}, input interface{}) *MockRotaDinamicaStore_Create_Call {
	return &MockRotaDinamicaStore_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockRotaDinamicaStore_Create_Call) Run(run func(ctx context.Context, input rotasdinamicas.RotaDinamicaInput)) *MockRotaDinamicaStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 rotasdinamicas.RotaDinamicaInput
		if args[1] != nil {
			arg1 = args[1].(rotasdinamicas.RotaDinamicaInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRotaDinamicaStore_Create_Call) Return(rotaDinamicaComDestinos *rotasdinamicas.RotaDinamicaComDestinos, err error) *MockRotaDinamicaStore_Create_Call {
	_c.Call.Return(rotaDinamicaComDestinos, err)
	return _c
}

func (_c *MockRotaDinamicaStore_Create_Call) RunAndReturn(run func(ctx context.Context, input rotasdinamicas.RotaDinamicaInput) (*rotasdinamicas.RotaDinamicaComDestinos, error)) *MockRotaDinamicaStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByViagem provides a mock function for the type MockRotaDinamicaStore
func (_mock *MockRotaDinamicaStore) DeleteByViagem(ctx context.Context, viagemID int64) error {
	ret := _mock.Called(ctx, viagemID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByViagem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, viagemID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRotaDinamicaStore_DeleteByViagem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByViagem'
type MockRotaDinamicaStore_DeleteByViagem_Call struct {
	*mock.Call
}

// DeleteByViagem is a helper method to define mock.On call
//   - ctx context.Context
//   - viagemID int64
func (_e *MockRotaDinamicaStore_Expecter) DeleteByViagem(ctx interface{}, viagemID interface{}) *MockRotaDinamicaStore_DeleteByViagem_Call {
	return &MockRotaDinamicaStore_DeleteByViagem_Call{Call: _e.mock.On("DeleteByViagem", ctx, viagemID)}
}

func (_c *MockRotaDinamicaStore_DeleteByViagem_Call) Run(run func(ctx context.Context, viagemID int64)) *MockRotaDinamicaStore_DeleteByViagem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRotaDinamicaStore_DeleteByViagem_Call) Return(err error) *MockRotaDinamicaStore_DeleteByViagem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRotaDinamicaStore_DeleteByViagem_Call) RunAndReturn(run func(ctx context.Context, viagemID int64) error) *MockRotaDinamicaStore_DeleteByViagem_Call {
	_c.Call.Return(run)
	return _c
}

// GetByViagem provides a mock function for the type MockRotaDinamicaStore
func (_mock *MockRotaDinamicaStore) GetByViagem(ctx context.Context, viagemID int64) (*rotasdinamicas.RotaDinamicaComDestinos, error) {
	ret := _mock.Called(ctx, viagemID)

	if len(ret) == 0 {
		panic("no return value specified for GetByViagem")
	}

	var r0 *rotasdinamicas.RotaDinamicaComDestinos
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*rotasdinamicas.RotaDinamicaComDestinos, error)); ok {
		return returnFunc(ctx, viagemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *rotasdinamicas.RotaDinamicaComDestinos); ok {
		r0 = returnFunc(ctx, viagemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rotasdinamicas.RotaDinamicaComDestinos)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, viagemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRotaDinamicaStore_GetByViagem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByViagem'
type MockRotaDinamicaStore_GetByViagem_Call struct {
	*mock.Call
}

// GetByViagem is a helper method to define mock.On call
//   - ctx context.Context
//   - viagemID int64
func (_e *MockRotaDinamicaStore_Expecter) GetByViagem(ctx interface{}, viagemID interface{}) *MockRotaDinamicaStore_GetByViagem_Call {
	return &MockRotaDinamicaStore_GetByViagem_Call{Call: _e.mock.On("GetByViagem", ctx, viagemID)}
}

func (_c *MockRotaDinamicaStore_GetByViagem_Call) Run(run func(ctx context.Context, viagemID int64)) *MockRotaDinamicaStore_GetByViagem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRotaDinamicaStore_GetByViagem_Call) Return(rotaDinamicaComDestinos *rotasdinamicas.RotaDinamicaComDestinos, err error) *MockRotaDinamicaStore_GetByViagem_Call {
	_c.Call.Return(rotaDinamicaComDestinos, err)
	return _c
}

func (_c *MockRotaDinamicaStore_GetByViagem_Call) RunAndReturn(run func(ctx context.Context, viagemID int64) (*rotasdinamicas.RotaDinamicaComDestinos, error)) *MockRotaDinamicaStore_GetByViagem_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpiresAtByViagem provides a mock function for the type MockRotaDinamicaStore
func (_mock *MockRotaDinamicaStore) GetExpiresAtByViagem(ctx context.Context, viagemID int64) (time.Time, error) {
	ret := _mock.Called(ctx, viagemID)

	if len(ret) == 0 {
		panic("no return value specified for GetExpiresAtByViagem")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (time.Time, error)); ok {
		return returnFunc(ctx, viagemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) time.Time); ok {
		r0 = returnFunc(ctx, viagemID)
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, viagemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRotaDinamicaStore_GetExpiresAtByViagem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpiresAtByViagem'
type MockRotaDinamicaStore_GetExpiresAtByViagem_Call struct {
	*mock.Call
}

// GetExpiresAtByViagem is a helper method to define mock.On call
//   - ctx context.Context
//   - viagemID int64
func (_e *MockRotaDinamicaStore_Expecter) GetExpiresAtByViagem(ctx interface{}, viagemID interface{}) *MockRotaDinamicaStore_GetExpiresAtByViagem_Call {
	return &MockRotaDinamicaStore_GetExpiresAtByViagem_Call{Call: _e.mock.On("GetExpiresAtByViagem", ctx, viagemID)}
}

func (_c *MockRotaDinamicaStore_GetExpiresAtByViagem_Call) Run(run func(ctx context.Context, viagemID int64)) *MockRotaDinamicaStore_GetExpiresAtByViagem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRotaDinamicaStore_GetExpiresAtByViagem_Call) Return(time1 time.Time, err error) *MockRotaDinamicaStore_GetExpiresAtByViagem_Call {
	_c.Call.Return(time1, err)
	return _c
}

func (_c *MockRotaDinamicaStore_GetExpiresAtByViagem_Call) RunAndReturn(run func(ctx context.Context, viagemID int64) (time.Time, error)) *MockRotaDinamicaStore_GetExpiresAtByViagem_Call {
	_c.Call.Return(run)
	return _c
}

// ListDestinos provides a mock function for the type MockRotaDinamicaStore
func (_mock *MockRotaDinamicaStore) ListDestinos(ctx context.Context, rotaDinamicaID int64) ([]rotasdinamicas.RotaDinamicaDestino, error) {
	ret := _mock.Called(ctx, rotaDinamicaID)

	if len(ret) == 0 {
		panic("no return value specified for ListDestinos")
	}

	var r0 []rotasdinamicas.RotaDinamicaDestino
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]rotasdinamicas.RotaDinamicaDestino, error)); ok {
		return returnFunc(ctx, rotaDinamicaID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []rotasdinamicas.RotaDinamicaDestino); ok {
		r0 = returnFunc(ctx, rotaDinamicaID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]rotasdinamicas.RotaDinamicaDestino)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, rotaDinamicaID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRotaDinamicaStore_ListDestinos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDestinos'
type MockRotaDinamicaStore_ListDestinos_Call struct {
	*mock.Call
}

// ListDestinos is a helper method to define mock.On call
//   - ctx context.Context
//   - rotaDinamicaID int64
func (_e *MockRotaDinamicaStore_Expecter) ListDestinos(ctx interface{}, rotaDinamicaID interface{}) *MockRotaDinamicaStore_ListDestinos_Call {
	return &MockRotaDinamicaStore_ListDestinos_Call{Call: _e.mock.On("ListDestinos", ctx, rotaDinamicaID)}
}

func (_c *MockRotaDinamicaStore_ListDestinos_Call) Run(run func(ctx context.Context, rotaDinamicaID int64)) *MockRotaDinamicaStore_ListDestinos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRotaDinamicaStore_ListDestinos_Call) Return(rotaDinamicaDestinos []rotasdinamicas.RotaDinamicaDestino, err error) *MockRotaDinamicaStore_ListDestinos_Call {
	_c.Call.Return(rotaDinamicaDestinos, err)
	return _c
}

func (_c *MockRotaDinamicaStore_ListDestinos_Call) RunAndReturn(run func(ctx context.Context, rotaDinamicaID int64) ([]rotasdinamicas.RotaDinamicaDestino, error)) *MockRotaDinamicaStore_ListDestinos_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRotaDinamicaService creates a new instance of MockRotaDinamicaService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRotaDinamicaService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRotaDinamicaService {
	mock := &MockRotaDinamicaService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRotaDinamicaService is an autogenerated mock type for the RotaDinamicaService type
type MockRotaDinamicaService struct {
	mock.Mock
}

type MockRotaDinamicaService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRotaDinamicaService) EXPECT() *MockRotaDinamicaService_Expecter {
	return &MockRotaDinamicaService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRotaDinamicaService
func (_mock *MockRotaDinamicaService) Create(ctx context.Context, input rotasdinamicas.RotaDinamicaInput) (*rotasdinamicas.RotaDinamicaComDestinos, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *rotasdinamicas.RotaDinamicaComDestinos
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, rotasdinamicas.RotaDinamicaInput) (*rotasdinamicas.RotaDinamicaComDestinos, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, rotasdinamicas.RotaDinamicaInput) *rotasdinamicas.RotaDinamicaComDestinos); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rotasdinamicas.RotaDinamicaComDestinos)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, rotasdinamicas.RotaDinamicaInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRotaDinamicaService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRotaDinamicaService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input rotasdinamicas.RotaDinamicaInput
func (_e *MockRotaDinamicaService_Expecter) Create(ctx interface{}, input interface{}) *MockRotaDinamicaService_Create_Call {
	return &MockRotaDinamicaService_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockRotaDinamicaService_Create_Call) Run(run func(ctx context.Context, input rotasdinamicas.RotaDinamicaInput)) *MockRotaDinamicaService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 rotasdinamicas.RotaDinamicaInput
		if args[1] != nil {
			arg1 = args[1].(rotasdinamicas.RotaDinamicaInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRotaDinamicaService_Create_Call) Return(rotaDinamicaComDestinos *rotasdinamicas.RotaDinamicaComDestinos, err error) *MockRotaDinamicaService_Create_Call {
	_c.Call.Return(rotaDinamicaComDestinos, err)
	return _c
}

func (_c *MockRotaDinamicaService_Create_Call) RunAndReturn(run func(ctx context.Context, input rotasdinamicas.RotaDinamicaInput) (*rotasdinamicas.RotaDinamicaComDestinos, error)) *MockRotaDinamicaService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByViagem provides a mock function for the type MockRotaDinamicaService
func (_mock *MockRotaDinamicaService) DeleteByViagem(ctx context.Context, viagemID int64) error {
	ret := _mock.Called(ctx, viagemID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByViagem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, viagemID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRotaDinamicaService_DeleteByViagem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByViagem'
type MockRotaDinamicaService_DeleteByViagem_Call struct {
	*mock.Call
}

// DeleteByViagem is a helper method to define mock.On call
//   - ctx context.Context
//   - viagemID int64
func (_e *MockRotaDinamicaService_Expecter) DeleteByViagem(ctx interface{}, viagemID interface{}) *MockRotaDinamicaService_DeleteByViagem_Call {
	return &MockRotaDinamicaService_DeleteByViagem_Call{Call: _e.mock.On("DeleteByViagem", ctx, viagemID)}
}

func (_c *MockRotaDinamicaService_DeleteByViagem_Call) Run(run func(ctx context.Context, viagemID int64)) *MockRotaDinamicaService_DeleteByViagem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRotaDinamicaService_DeleteByViagem_Call) Return(err error) *MockRotaDinamicaService_DeleteByViagem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRotaDinamicaService_DeleteByViagem_Call) RunAndReturn(run func(ctx context.Context, viagemID int64) error) *MockRotaDinamicaService_DeleteByViagem_Call {
	_c.Call.Return(run)
	return _c
}

// GetByViagem provides a mock function for the type MockRotaDinamicaService
func (_mock *MockRotaDinamicaService) GetByViagem(ctx context.Context, viagemID int64) (*rotasdinamicas.RotaDinamicaComDestinos, error) {
	ret := _mock.Called(ctx, viagemID)

	if len(ret) == 0 {
		panic("no return value specified for GetByViagem")
	}

	var r0 *rotasdinamicas.RotaDinamicaComDestinos
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*rotasdinamicas.RotaDinamicaComDestinos, error)); ok {
		return returnFunc(ctx, viagemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *rotasdinamicas.RotaDinamicaComDestinos); ok {
		r0 = returnFunc(ctx, viagemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rotasdinamicas.RotaDinamicaComDestinos)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, viagemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRotaDinamicaService_GetByViagem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByViagem'
type MockRotaDinamicaService_GetByViagem_Call struct {
	*mock.Call
}

// GetByViagem is a helper method to define mock.On call
//   - ctx context.Context
//   - viagemID int64
func (_e *MockRotaDinamicaService_Expecter) GetByViagem(ctx interface{}, viagemID interface{}) *MockRotaDinamicaService_GetByViagem_Call {
	return &MockRotaDinamicaService_GetByViagem_Call{Call: _e.mock.On("GetByViagem", ctx, viagemID)}
}

func (_c *MockRotaDinamicaService_GetByViagem_Call) Run(run func(ctx context.Context, viagemID int64)) *MockRotaDinamicaService_GetByViagem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRotaDinamicaService_GetByViagem_Call) Return(rotaDinamicaComDestinos *rotasdinamicas.RotaDinamicaComDestinos, err error) *MockRotaDinamicaService_GetByViagem_Call {
	_c.Call.Return(rotaDinamicaComDestinos, err)
	return _c
}

func (_c *MockRotaDinamicaService_GetByViagem_Call) RunAndReturn(run func(ctx context.Context, viagemID int64) (*rotasdinamicas.RotaDinamicaComDestinos, error)) *MockRotaDinamicaService_GetByViagem_Call {
	_c.Call.Return(run)
	return _c
}
