// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fredsaggio/bondrota-api/internal/veiculos"
	mock "github.com/stretchr/testify/mock"
)

// NewMockVeiculoStore creates a new instance of MockVeiculoStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVeiculoStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVeiculoStore {
	mock := &MockVeiculoStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVeiculoStore is an autogenerated mock type for the VeiculoStore type
type MockVeiculoStore struct {
	mock.Mock
}

type MockVeiculoStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVeiculoStore) EXPECT() *MockVeiculoStore_Expecter {
	return &MockVeiculoStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockVeiculoStore
func (_mock *MockVeiculoStore) Create(ctx context.Context, input veiculos.VeiculoInput) (*veiculos.Veiculo, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *veiculos.Veiculo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, veiculos.VeiculoInput) (*veiculos.Veiculo, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, veiculos.VeiculoInput) *veiculos.Veiculo); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*veiculos.Veiculo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, veiculos.VeiculoInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVeiculoStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockVeiculoStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input veiculos.VeiculoInput
func (_e *MockVeiculoStore_Expecter) Create(ctx interface{}, input interface{}) *MockVeiculoStore_Create_Call {
	return &MockVeiculoStore_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockVeiculoStore_Create_Call) Run(run func(ctx context.Context, input veiculos.VeiculoInput)) *MockVeiculoStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 veiculos.VeiculoInput
		if args[1] != nil {
			arg1 = args[1].(veiculos.VeiculoInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVeiculoStore_Create_Call) Return(veiculo *veiculos.Veiculo, err error) *MockVeiculoStore_Create_Call {
	_c.Call.Return(veiculo, err)
	return _c
}

func (_c *MockVeiculoStore_Create_Call) RunAndReturn(run func(ctx context.Context, input veiculos.VeiculoInput) (*veiculos.Veiculo, error)) *MockVeiculoStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockVeiculoStore
func (_mock *MockVeiculoStore) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVeiculoStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockVeiculoStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockVeiculoStore_Expecter) Delete(ctx interface{}, id interface{}) *MockVeiculoStore_Delete_Call {
	return &MockVeiculoStore_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockVeiculoStore_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockVeiculoStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVeiculoStore_Delete_Call) Return(err error) *MockVeiculoStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVeiculoStore_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockVeiculoStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockVeiculoStore
func (_mock *MockVeiculoStore) GetByID(ctx context.Context, id int64) (*veiculos.Veiculo, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *veiculos.Veiculo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*veiculos.Veiculo, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *veiculos.Veiculo); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*veiculos.Veiculo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVeiculoStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockVeiculoStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockVeiculoStore_Expecter) GetByID(ctx interface{}, id interface{}) *MockVeiculoStore_GetByID_Call {
	return &MockVeiculoStore_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockVeiculoStore_GetByID_Call) Run(run func(ctx context.Context, id int64)) *MockVeiculoStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVeiculoStore_GetByID_Call) Return(veiculo *veiculos.Veiculo, err error) *MockVeiculoStore_GetByID_Call {
	_c.Call.Return(veiculo, err)
	return _c
}

func (_c *MockVeiculoStore_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*veiculos.Veiculo, error)) *MockVeiculoStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockVeiculoStore
func (_mock *MockVeiculoStore) List(ctx context.Context) ([]veiculos.Veiculo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []veiculos.Veiculo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]veiculos.Veiculo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []veiculos.Veiculo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]veiculos.Veiculo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVeiculoStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockVeiculoStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockVeiculoStore_Expecter) List(ctx interface{}) *MockVeiculoStore_List_Call {
	return &MockVeiculoStore_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockVeiculoStore_List_Call) Run(run func(ctx context.Context)) *MockVeiculoStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVeiculoStore_List_Call) Return(veiculos1 []veiculos.Veiculo, err error) *MockVeiculoStore_List_Call {
	_c.Call.Return(veiculos1, err)
	return _c
}

func (_c *MockVeiculoStore_List_Call) RunAndReturn(run func(ctx context.Context) ([]veiculos.Veiculo, error)) *MockVeiculoStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockVeiculoStore
func (_mock *MockVeiculoStore) Update(ctx context.Context, id int64, updateFunc func(*veiculos.Veiculo) (bool, error)) (*veiculos.Veiculo, error) {
	ret := _mock.Called(ctx, id, updateFunc)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *veiculos.Veiculo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, func(*veiculos.Veiculo) (bool, error)) (*veiculos.Veiculo, error)); ok {
		return returnFunc(ctx, id, updateFunc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, func(*veiculos.Veiculo) (bool, error)) *veiculos.Veiculo); ok {
		r0 = returnFunc(ctx, id, updateFunc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*veiculos.Veiculo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, func(*veiculos.Veiculo) (bool, error)) error); ok {
		r1 = returnFunc(ctx, id, updateFunc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVeiculoStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockVeiculoStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - updateFunc func(*veiculos.Veiculo) (bool, error)
func (_e *MockVeiculoStore_Expecter) Update(ctx interface{}, id interface{}, updateFunc interface{}) *MockVeiculoStore_Update_Call {
	return &MockVeiculoStore_Update_Call{Call: _e.mock.On("Update", ctx, id, updateFunc)}
}

func (_c *MockVeiculoStore_Update_Call) Run(run func(ctx context.Context, id int64, updateFunc func(*veiculos.Veiculo) (bool, error))) *MockVeiculoStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 func(*veiculos.Veiculo) (bool, error)
		if args[2] != nil {
			arg2 = args[2].(func(*veiculos.Veiculo) (bool, error))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVeiculoStore_Update_Call) Return(veiculo *veiculos.Veiculo, err error) *MockVeiculoStore_Update_Call {
	_c.Call.Return(veiculo, err)
	return _c
}

func (_c *MockVeiculoStore_Update_Call) RunAndReturn(run func(ctx context.Context, id int64, updateFunc func(*veiculos.Veiculo) (bool, error)) (*veiculos.Veiculo, error)) *MockVeiculoStore_Update_Call {
	_c.Call.Return(run)
	return _c
}
