// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/fredsaggio/bondrota-api/internal/viagens"
	mock "github.com/stretchr/testify/mock"
)

// NewMockViagemStore creates a new instance of MockViagemStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockViagemStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockViagemStore {
	mock := &MockViagemStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockViagemStore is an autogenerated mock type for the ViagemStore type
type MockViagemStore struct {
	mock.Mock
}

type MockViagemStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockViagemStore) EXPECT() *MockViagemStore_Expecter {
	return &MockViagemStore_Expecter{mock: &_m.Mock}
}

// AtualizarStatusERegistrarHorarioViagem provides a mock function for the type MockViagemStore
func (_mock *MockViagemStore) AtualizarStatusERegistrarHorarioViagem(ctx context.Context, viagemID int64, from viagens.StatusViagem, to viagens.StatusViagem, tipo viagens.TipoHorarioViagem, horario time.Time) (*viagens.Viagem, error) {
	ret := _mock.Called(ctx, viagemID, from, to, tipo, horario)

	if len(ret) == 0 {
		panic("no return value specified for AtualizarStatusERegistrarHorarioViagem")
	}

	var r0 *viagens.Viagem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, viagens.StatusViagem, viagens.StatusViagem, viagens.TipoHorarioViagem, time.Time) (*viagens.Viagem, error)); ok {
		return returnFunc(ctx, viagemID, from, to, tipo, horario)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, viagens.StatusViagem, viagens.StatusViagem, viagens.TipoHorarioViagem, time.Time) *viagens.Viagem); ok {
		r0 = returnFunc(ctx, viagemID, from, to, tipo, horario)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*viagens.Viagem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, viagens.StatusViagem, viagens.StatusViagem, viagens.TipoHorarioViagem, time.Time) error); ok {
		r1 = returnFunc(ctx, viagemID, from, to, tipo, horario)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockViagemStore_AtualizarStatusERegistrarHorarioViagem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AtualizarStatusERegistrarHorarioViagem'
type MockViagemStore_AtualizarStatusERegistrarHorarioViagem_Call struct {
	*mock.Call
}

// AtualizarStatusERegistrarHorarioViagem is a helper method to define mock.On call
//   - ctx context.Context
//   - viagemID int64
//   - from viagens.StatusViagem
//   - to viagens.StatusViagem
//   - tipo viagens.TipoHorarioViagem
//   - horario time.Time
func (_e *MockViagemStore_Expecter) AtualizarStatusERegistrarHorarioViagem(ctx interface{}, viagemID interface{}, from interface{}, to interface{}, tipo interface{}, horario interface{}) *MockViagemStore_AtualizarStatusERegistrarHorarioViagem_Call {
	return &MockViagemStore_AtualizarStatusERegistrarHorarioViagem_Call{Call: _e.mock.On("AtualizarStatusERegistrarHorarioViagem", ctx, viagemID, from, to, tipo, horario)}
}

func (_c *MockViagemStore_AtualizarStatusERegistrarHorarioViagem_Call) Run(run func(ctx context.Context, viagemID int64, from viagens.StatusViagem, to viagens.StatusViagem, tipo viagens.TipoHorarioViagem, horario time.Time)) *MockViagemStore_AtualizarStatusERegistrarHorarioViagem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 viagens.StatusViagem
		if args[2] != nil {
			arg2 = args[2].(viagens.StatusViagem)
		}
		var arg3 viagens.StatusViagem
		if args[3] != nil {
			arg3 = args[3].(viagens.StatusViagem)
		}
		var arg4 viagens.TipoHorarioViagem
		if args[4] != nil {
			arg4 = args[4].(viagens.TipoHorarioViagem)
		}
		var arg5 time.Time
		if args[5] != nil {
			arg5 = args[5].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockViagemStore_AtualizarStatusERegistrarHorarioViagem_Call) Return(viagem *viagens.Viagem, err error) *MockViagemStore_AtualizarStatusERegistrarHorarioViagem_Call {
	_c.Call.Return(viagem, err)
	return _c
}

func (_c *MockViagemStore_AtualizarStatusERegistrarHorarioViagem_Call) RunAndReturn(run func(ctx context.Context, viagemID int64, from viagens.StatusViagem, to viagens.StatusViagem, tipo viagens.TipoHorarioViagem, horario time.Time) (*viagens.Viagem, error)) *MockViagemStore_AtualizarStatusERegistrarHorarioViagem_Call {
	_c.Call.Return(run)
	return _c
}

// CreateViagem provides a mock function for the type MockViagemStore
func (_mock *MockViagemStore) CreateViagem(ctx context.Context, input viagens.ViagemInput) (*viagens.Viagem, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateViagem")
	}

	var r0 *viagens.Viagem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, viagens.ViagemInput) (*viagens.Viagem, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, viagens.ViagemInput) *viagens.Viagem); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*viagens.Viagem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, viagens.ViagemInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockViagemStore_CreateViagem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateViagem'
type MockViagemStore_CreateViagem_Call struct {
	*mock.Call
}

// CreateViagem is a helper method to define mock.On call
//   - ctx context.Context
//   - input viagens.ViagemInput
func (_e *MockViagemStore_Expecter) CreateViagem(ctx interface{}, input interface{}) *MockViagemStore_CreateViagem_Call {
	return &MockViagemStore_CreateViagem_Call{Call: _e.mock.On("CreateViagem", ctx, input)}
}

func (_c *MockViagemStore_CreateViagem_Call) Run(run func(ctx context.Context, input viagens.ViagemInput)) *MockViagemStore_CreateViagem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 viagens.ViagemInput
		if args[1] != nil {
			arg1 = args[1].(viagens.ViagemInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockViagemStore_CreateViagem_Call) Return(viagem *viagens.Viagem, err error) *MockViagemStore_CreateViagem_Call {
	_c.Call.Return(viagem, err)
	return _c
}

func (_c *MockViagemStore_CreateViagem_Call) RunAndReturn(run func(ctx context.Context, input viagens.ViagemInput) (*viagens.Viagem, error)) *MockViagemStore_CreateViagem_Call {
	_c.Call.Return(run)
	return _c
}

// GetViagemByID provides a mock function for the type MockViagemStore
func (_mock *MockViagemStore) GetViagemByID(ctx context.Context, viagemID int64) (*viagens.ViagemComCiclo, error) {
	ret := _mock.Called(ctx, viagemID)

	if len(ret) == 0 {
		panic("no return value specified for GetViagemByID")
	}

	var r0 *viagens.ViagemComCiclo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*viagens.ViagemComCiclo, error)); ok {
		return returnFunc(ctx, viagemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *viagens.ViagemComCiclo); ok {
		r0 = returnFunc(ctx, viagemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*viagens.ViagemComCiclo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, viagemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockViagemStore_GetViagemByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetViagemByID'
type MockViagemStore_GetViagemByID_Call struct {
	*mock.Call
}

// GetViagemByID is a helper method to define mock.On call
//   - ctx context.Context
//   - viagemID int64
func (_e *MockViagemStore_Expecter) GetViagemByID(ctx interface{}, viagemID interface{}) *MockViagemStore_GetViagemByID_Call {
	return &MockViagemStore_GetViagemByID_Call{Call: _e.mock.On("GetViagemByID", ctx, viagemID)}
}

func (_c *MockViagemStore_GetViagemByID_Call) Run(run func(ctx context.Context, viagemID int64)) *MockViagemStore_GetViagemByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockViagemStore_GetViagemByID_Call) Return(viagemComCiclo *viagens.ViagemComCiclo, err error) *MockViagemStore_GetViagemByID_Call {
	_c.Call.Return(viagemComCiclo, err)
	return _c
}

func (_c *MockViagemStore_GetViagemByID_Call) RunAndReturn(run func(ctx context.Context, viagemID int64) (*viagens.ViagemComCiclo, error)) *MockViagemStore_GetViagemByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListHorariosByViagem provides a mock function for the type MockViagemStore
func (_mock *MockViagemStore) ListHorariosByViagem(ctx context.Context, viagemID int64) ([]viagens.ViagemHorario, error) {
	ret := _mock.Called(ctx, viagemID)

	if len(ret) == 0 {
		panic("no return value specified for ListHorariosByViagem")
	}

	var r0 []viagens.ViagemHorario
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]viagens.ViagemHorario, error)); ok {
		return returnFunc(ctx, viagemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []viagens.ViagemHorario); ok {
		r0 = returnFunc(ctx, viagemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]viagens.ViagemHorario)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, viagemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockViagemStore_ListHorariosByViagem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHorariosByViagem'
type MockViagemStore_ListHorariosByViagem_Call struct {
	*mock.Call
}

// ListHorariosByViagem is a helper method to define mock.On call
//   - ctx context.Context
//   - viagemID int64
func (_e *MockViagemStore_Expecter) ListHorariosByViagem(ctx interface{}, viagemID interface{}) *MockViagemStore_ListHorariosByViagem_Call {
	return &MockViagemStore_ListHorariosByViagem_Call{Call: _e.mock.On("ListHorariosByViagem", ctx, viagemID)}
}

func (_c *MockViagemStore_ListHorariosByViagem_Call) Run(run func(ctx context.Context, viagemID int64)) *MockViagemStore_ListHorariosByViagem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockViagemStore_ListHorariosByViagem_Call) Return(viagemHorarios []viagens.ViagemHorario, err error) *MockViagemStore_ListHorariosByViagem_Call {
	_c.Call.Return(viagemHorarios, err)
	return _c
}

func (_c *MockViagemStore_ListHorariosByViagem_Call) RunAndReturn(run func(ctx context.Context, viagemID int64) ([]viagens.ViagemHorario, error)) *MockViagemStore_ListHorariosByViagem_Call {
	_c.Call.Return(run)
	return _c
}

// ListViagens provides a mock function for the type MockViagemStore
func (_mock *MockViagemStore) ListViagens(ctx context.Context, params viagens.ViagemListParams) (viagens.ViagemListResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListViagens")
	}

	var r0 viagens.ViagemListResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, viagens.ViagemListParams) (viagens.ViagemListResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, viagens.ViagemListParams) viagens.ViagemListResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(viagens.ViagemListResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, viagens.ViagemListParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockViagemStore_ListViagens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListViagens'
type MockViagemStore_ListViagens_Call struct {
	*mock.Call
}

// ListViagens is a helper method to define mock.On call
//   - ctx context.Context
//   - params viagens.ViagemListParams
func (_e *MockViagemStore_Expecter) ListViagens(ctx interface{}, params interface{}) *MockViagemStore_ListViagens_Call {
	return &MockViagemStore_ListViagens_Call{Call: _e.mock.On("ListViagens", ctx, params)}
}

func (_c *MockViagemStore_ListViagens_Call) Run(run func(ctx context.Context, params viagens.ViagemListParams)) *MockViagemStore_ListViagens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 viagens.ViagemListParams
		if args[1] != nil {
			arg1 = args[1].(viagens.ViagemListParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockViagemStore_ListViagens_Call) Return(viagemListResult viagens.ViagemListResult, err error) *MockViagemStore_ListViagens_Call {
	_c.Call.Return(viagemListResult, err)
	return _c
}

func (_c *MockViagemStore_ListViagens_Call) RunAndReturn(run func(ctx context.Context, params viagens.ViagemListParams) (viagens.ViagemListResult, error)) *MockViagemStore_ListViagens_Call {
	_c.Call.Return(run)
	return _c
}

// ListViagensByCiclo provides a mock function for the type MockViagemStore
func (_mock *MockViagemStore) ListViagensByCiclo(ctx context.Context, cicloID int64) ([]viagens.Viagem, error) {
	ret := _mock.Called(ctx, cicloID)

	if len(ret) == 0 {
		panic("no return value specified for ListViagensByCiclo")
	}

	var r0 []viagens.Viagem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]viagens.Viagem, error)); ok {
		return returnFunc(ctx, cicloID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []viagens.Viagem); ok {
		r0 = returnFunc(ctx, cicloID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]viagens.Viagem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, cicloID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockViagemStore_ListViagensByCiclo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListViagensByCiclo'
type MockViagemStore_ListViagensByCiclo_Call struct {
	*mock.Call
}

// ListViagensByCiclo is a helper method to define mock.On call
//   - ctx context.Context
//   - cicloID int64
func (_e *MockViagemStore_Expecter) ListViagensByCiclo(ctx interface{}, cicloID interface{}) *MockViagemStore_ListViagensByCiclo_Call {
	return &MockViagemStore_ListViagensByCiclo_Call{Call: _e.mock.On("ListViagensByCiclo", ctx, cicloID)}
}

func (_c *MockViagemStore_ListViagensByCiclo_Call) Run(run func(ctx context.Context, cicloID int64)) *MockViagemStore_ListViagensByCiclo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockViagemStore_ListViagensByCiclo_Call) Return(viagems []viagens.Viagem, err error) *MockViagemStore_ListViagensByCiclo_Call {
	_c.Call.Return(viagems, err)
	return _c
}

func (_c *MockViagemStore_ListViagensByCiclo_Call) RunAndReturn(run func(ctx context.Context, cicloID int64) ([]viagens.Viagem, error)) *MockViagemStore_ListViagensByCiclo_Call {
	_c.Call.Return(run)
	return _c
}

// RegistrarHorarioViagem provides a mock function for the type MockViagemStore
func (_mock *MockViagemStore) RegistrarHorarioViagem(ctx context.Context, viagemID int64, tipo viagens.TipoHorarioViagem, horario time.Time) (*viagens.ViagemHorario, error) {
	ret := _mock.Called(ctx, viagemID, tipo, horario)

	if len(ret) == 0 {
		panic("no return value specified for RegistrarHorarioViagem")
	}

	var r0 *viagens.ViagemHorario
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, viagens.TipoHorarioViagem, time.Time) (*viagens.ViagemHorario, error)); ok {
		return returnFunc(ctx, viagemID, tipo, horario)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, viagens.TipoHorarioViagem, time.Time) *viagens.ViagemHorario); ok {
		r0 = returnFunc(ctx, viagemID, tipo, horario)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*viagens.ViagemHorario)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, viagens.TipoHorarioViagem, time.Time) error); ok {
		r1 = returnFunc(ctx, viagemID, tipo, horario)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockViagemStore_RegistrarHorarioViagem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegistrarHorarioViagem'
type MockViagemStore_RegistrarHorarioViagem_Call struct {
	*mock.Call
}

// RegistrarHorarioViagem is a helper method to define mock.On call
//   - ctx context.Context
//   - viagemID int64
//   - tipo viagens.TipoHorarioViagem
//   - horario time.Time
func (_e *MockViagemStore_Expecter) RegistrarHorarioViagem(ctx interface{}, viagemID interface{}, tipo interface{}, horario interface{}) *MockViagemStore_RegistrarHorarioViagem_Call {
	return &MockViagemStore_RegistrarHorarioViagem_Call{Call: _e.mock.On("RegistrarHorarioViagem", ctx, viagemID, tipo, horario)}
}

func (_c *MockViagemStore_RegistrarHorarioViagem_Call) Run(run func(ctx context.Context, viagemID int64, tipo viagens.TipoHorarioViagem, horario time.Time)) *MockViagemStore_RegistrarHorarioViagem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 viagens.TipoHorarioViagem
		if args[2] != nil {
			arg2 = args[2].(viagens.TipoHorarioViagem)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockViagemStore_RegistrarHorarioViagem_Call) Return(viagemHorario *viagens.ViagemHorario, err error) *MockViagemStore_RegistrarHorarioViagem_Call {
	_c.Call.Return(viagemHorario, err)
	return _c
}

func (_c *MockViagemStore_RegistrarHorarioViagem_Call) RunAndReturn(run func(ctx context.Context, viagemID int64, tipo viagens.TipoHorarioViagem, horario time.Time) (*viagens.ViagemHorario, error)) *MockViagemStore_RegistrarHorarioViagem_Call {
	_c.Call.Return(run)
	return _c
}

// ResumoViagens provides a mock function for the type MockViagemStore
func (_mock *MockViagemStore) ResumoViagens(ctx context.Context, hoje time.Time) (viagens.ViagemResumo, error) {
	ret := _mock.Called(ctx, hoje)

	if len(ret) == 0 {
		panic("no return value specified for ResumoViagens")
	}

	var r0 viagens.ViagemResumo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) (viagens.ViagemResumo, error)); ok {
		return returnFunc(ctx, hoje)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) viagens.ViagemResumo); ok {
		r0 = returnFunc(ctx, hoje)
	} else {
		r0 = ret.Get(0).(viagens.ViagemResumo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, hoje)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockViagemStore_ResumoViagens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResumoViagens'
type MockViagemStore_ResumoViagens_Call struct {
	*mock.Call
}

// ResumoViagens is a helper method to define mock.On call
//   - ctx context.Context
//   - hoje time.Time
func (_e *MockViagemStore_Expecter) ResumoViagens(ctx interface{}, hoje interface{}) *MockViagemStore_ResumoViagens_Call {
	return &MockViagemStore_ResumoViagens_Call{Call: _e.mock.On("ResumoViagens", ctx, hoje)}
}

func (_c *MockViagemStore_ResumoViagens_Call) Run(run func(ctx context.Context, hoje time.Time)) *MockViagemStore_ResumoViagens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockViagemStore_ResumoViagens_Call) Return(viagemResumo viagens.ViagemResumo, err error) *MockViagemStore_ResumoViagens_Call {
	_c.Call.Return(viagemResumo, err)
	return _c
}

func (_c *MockViagemStore_ResumoViagens_Call) RunAndReturn(run func(ctx context.Context, hoje time.Time) (viagens.ViagemResumo, error)) *MockViagemStore_ResumoViagens_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateViagem provides a mock function for the type MockViagemStore
func (_mock *MockViagemStore) UpdateViagem(ctx context.Context, viagemID int64, updateFunc func(*viagens.Viagem) (bool, error)) (*viagens.Viagem, error) {
	ret := _mock.Called(ctx, viagemID, updateFunc)

	if len(ret) == 0 {
		panic("no return value specified for UpdateViagem")
	}

	var r0 *viagens.Viagem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, func(*viagens.Viagem) (bool, error)) (*viagens.Viagem, error)); ok {
		return returnFunc(ctx, viagemID, updateFunc)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, func(*viagens.Viagem) (bool, error)) *viagens.Viagem); ok {
		r0 = returnFunc(ctx, viagemID, updateFunc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*viagens.Viagem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, func(*viagens.Viagem) (bool, error)) error); ok {
		r1 = returnFunc(ctx, viagemID, updateFunc)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockViagemStore_UpdateViagem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateViagem'
type MockViagemStore_UpdateViagem_Call struct {
	*mock.Call
}

// UpdateViagem is a helper method to define mock.On call
//   - ctx context.Context
//   - viagemID int64
//   - updateFunc func(*viagens.Viagem) (bool, error)
func (_e *MockViagemStore_Expecter) UpdateViagem(ctx interface{}, viagemID interface{}, updateFunc interface{}) *MockViagemStore_UpdateViagem_Call {
	return &MockViagemStore_UpdateViagem_Call{Call: _e.mock.On("UpdateViagem", ctx, viagemID, updateFunc)}
}

func (_c *MockViagemStore_UpdateViagem_Call) Run(run func(ctx context.Context, viagemID int64, updateFunc func(*viagens.Viagem) (bool, error))) *MockViagemStore_UpdateViagem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 func(*viagens.Viagem) (bool, error)
		if args[2] != nil {
			arg2 = args[2].(func(*viagens.Viagem) (bool, error))
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockViagemStore_UpdateViagem_Call) Return(viagem *viagens.Viagem, err error) *MockViagemStore_UpdateViagem_Call {
	_c.Call.Return(viagem, err)
	return _c
}

func (_c *MockViagemStore_UpdateViagem_Call) RunAndReturn(run func(ctx context.Context, viagemID int64, updateFunc func(*viagens.Viagem) (bool, error)) (*viagens.Viagem, error)) *MockViagemStore_UpdateViagem_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockViagemService creates a new instance of MockViagemService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockViagemService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockViagemService {
	mock := &MockViagemService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockViagemService is an autogenerated mock type for the ViagemService type
type MockViagemService struct {
	mock.Mock
}

type MockViagemService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockViagemService) EXPECT() *MockViagemService_Expecter {
	return &MockViagemService_Expecter{mock: &_m.Mock}
}

// Cancelar provides a mock function for the type MockViagemService
func (_mock *MockViagemService) Cancelar(ctx context.Context, viagemID int64) (*viagens.Viagem, error) {
	ret := _mock.Called(ctx, viagemID)

	if len(ret) == 0 {
		panic("no return value specified for Cancelar")
	}

	var r0 *viagens.Viagem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*viagens.Viagem, error)); ok {
		return returnFunc(ctx, viagemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *viagens.Viagem); ok {
		r0 = returnFunc(ctx, viagemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*viagens.Viagem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, viagemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockViagemService_Cancelar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancelar'
type MockViagemService_Cancelar_Call struct {
	*mock.Call
}

// Cancelar is a helper method to define mock.On call
//   - ctx context.Context
//   - viagemID int64
func (_e *MockViagemService_Expecter) Cancelar(ctx interface{}, viagemID interface{}) *MockViagemService_Cancelar_Call {
	return &MockViagemService_Cancelar_Call{Call: _e.mock.On("Cancelar", ctx, viagemID)}
}

func (_c *MockViagemService_Cancelar_Call) Run(run func(ctx context.Context, viagemID int64)) *MockViagemService_Cancelar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockViagemService_Cancelar_Call) Return(viagem *viagens.Viagem, err error) *MockViagemService_Cancelar_Call {
	_c.Call.Return(viagem, err)
	return _c
}

func (_c *MockViagemService_Cancelar_Call) RunAndReturn(run func(ctx context.Context, viagemID int64) (*viagens.Viagem, error)) *MockViagemService_Cancelar_Call {
	_c.Call.Return(run)
	return _c
}

// Concluir provides a mock function for the type MockViagemService
func (_mock *MockViagemService) Concluir(ctx context.Context, viagemID int64) (*viagens.Viagem, error) {
	ret := _mock.Called(ctx, viagemID)

	if len(ret) == 0 {
		panic("no return value specified for Concluir")
	}

	var r0 *viagens.Viagem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*viagens.Viagem, error)); ok {
		return returnFunc(ctx, viagemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *viagens.Viagem); ok {
		r0 = returnFunc(ctx, viagemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*viagens.Viagem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, viagemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockViagemService_Concluir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Concluir'
type MockViagemService_Concluir_Call struct {
	*mock.Call
}

// Concluir is a helper method to define mock.On call
//   - ctx context.Context
//   - viagemID int64
func (_e *MockViagemService_Expecter) Concluir(ctx interface{}, viagemID interface{}) *MockViagemService_Concluir_Call {
	return &MockViagemService_Concluir_Call{Call: _e.mock.On("Concluir", ctx, viagemID)}
}

func (_c *MockViagemService_Concluir_Call) Run(run func(ctx context.Context, viagemID int64)) *MockViagemService_Concluir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockViagemService_Concluir_Call) Return(viagem *viagens.Viagem, err error) *MockViagemService_Concluir_Call {
	_c.Call.Return(viagem, err)
	return _c
}

func (_c *MockViagemService_Concluir_Call) RunAndReturn(run func(ctx context.Context, viagemID int64) (*viagens.Viagem, error)) *MockViagemService_Concluir_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockViagemService
func (_mock *MockViagemService) GetByID(ctx context.Context, viagemID int64) (*viagens.ViagemComCiclo, error) {
	ret := _mock.Called(ctx, viagemID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *viagens.ViagemComCiclo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*viagens.ViagemComCiclo, error)); ok {
		return returnFunc(ctx, viagemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *viagens.ViagemComCiclo); ok {
		r0 = returnFunc(ctx, viagemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*viagens.ViagemComCiclo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, viagemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockViagemService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockViagemService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - viagemID int64
func (_e *MockViagemService_Expecter) GetByID(ctx interface{}, viagemID interface{}) *MockViagemService_GetByID_Call {
	return &MockViagemService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, viagemID)}
}

func (_c *MockViagemService_GetByID_Call) Run(run func(ctx context.Context, viagemID int64)) *MockViagemService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockViagemService_GetByID_Call) Return(viagemComCiclo *viagens.ViagemComCiclo, err error) *MockViagemService_GetByID_Call {
	_c.Call.Return(viagemComCiclo, err)
	return _c
}

func (_c *MockViagemService_GetByID_Call) RunAndReturn(run func(ctx context.Context, viagemID int64) (*viagens.ViagemComCiclo, error)) *MockViagemService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Iniciar provides a mock function for the type MockViagemService
func (_mock *MockViagemService) Iniciar(ctx context.Context, viagemID int64) (*viagens.Viagem, error) {
	ret := _mock.Called(ctx, viagemID)

	if len(ret) == 0 {
		panic("no return value specified for Iniciar")
	}

	var r0 *viagens.Viagem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*viagens.Viagem, error)); ok {
		return returnFunc(ctx, viagemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *viagens.Viagem); ok {
		r0 = returnFunc(ctx, viagemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*viagens.Viagem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, viagemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockViagemService_Iniciar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Iniciar'
type MockViagemService_Iniciar_Call struct {
	*mock.Call
}

// Iniciar is a helper method to define mock.On call
//   - ctx context.Context
//   - viagemID int64
func (_e *MockViagemService_Expecter) Iniciar(ctx interface{}, viagemID interface{}) *MockViagemService_Iniciar_Call {
	return &MockViagemService_Iniciar_Call{Call: _e.mock.On("Iniciar", ctx, viagemID)}
}

func (_c *MockViagemService_Iniciar_Call) Run(run func(ctx context.Context, viagemID int64)) *MockViagemService_Iniciar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockViagemService_Iniciar_Call) Return(viagem *viagens.Viagem, err error) *MockViagemService_Iniciar_Call {
	_c.Call.Return(viagem, err)
	return _c
}

func (_c *MockViagemService_Iniciar_Call) RunAndReturn(run func(ctx context.Context, viagemID int64) (*viagens.Viagem, error)) *MockViagemService_Iniciar_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockViagemService
func (_mock *MockViagemService) List(ctx context.Context, params viagens.ViagemListParams) (viagens.ViagemListResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 viagens.ViagemListResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, viagens.ViagemListParams) (viagens.ViagemListResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, viagens.ViagemListParams) viagens.ViagemListResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Get(0).(viagens.ViagemListResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, viagens.ViagemListParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockViagemService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockViagemService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - params viagens.ViagemListParams
func (_e *MockViagemService_Expecter) List(ctx interface{}, params interface{}) *MockViagemService_List_Call {
	return &MockViagemService_List_Call{Call: _e.mock.On("List", ctx, params)}
}

func (_c *MockViagemService_List_Call) Run(run func(ctx context.Context, params viagens.ViagemListParams)) *MockViagemService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 viagens.ViagemListParams
		if args[1] != nil {
			arg1 = args[1].(viagens.ViagemListParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockViagemService_List_Call) Return(viagemListResult viagens.ViagemListResult, err error) *MockViagemService_List_Call {
	_c.Call.Return(viagemListResult, err)
	return _c
}

func (_c *MockViagemService_List_Call) RunAndReturn(run func(ctx context.Context, params viagens.ViagemListParams) (viagens.ViagemListResult, error)) *MockViagemService_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListHorariosByViagem provides a mock function for the type MockViagemService
func (_mock *MockViagemService) ListHorariosByViagem(ctx context.Context, viagemID int64) ([]viagens.ViagemHorario, error) {
	ret := _mock.Called(ctx, viagemID)

	if len(ret) == 0 {
		panic("no return value specified for ListHorariosByViagem")
	}

	var r0 []viagens.ViagemHorario
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]viagens.ViagemHorario, error)); ok {
		return returnFunc(ctx, viagemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []viagens.ViagemHorario); ok {
		r0 = returnFunc(ctx, viagemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]viagens.ViagemHorario)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, viagemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockViagemService_ListHorariosByViagem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListHorariosByViagem'
type MockViagemService_ListHorariosByViagem_Call struct {
	*mock.Call
}

// ListHorariosByViagem is a helper method to define mock.On call
//   - ctx context.Context
//   - viagemID int64
func (_e *MockViagemService_Expecter) ListHorariosByViagem(ctx interface{}, viagemID interface{}) *MockViagemService_ListHorariosByViagem_Call {
	return &MockViagemService_ListHorariosByViagem_Call{Call: _e.mock.On("ListHorariosByViagem", ctx, viagemID)}
}

func (_c *MockViagemService_ListHorariosByViagem_Call) Run(run func(ctx context.Context, viagemID int64)) *MockViagemService_ListHorariosByViagem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockViagemService_ListHorariosByViagem_Call) Return(viagemHorarios []viagens.ViagemHorario, err error) *MockViagemService_ListHorariosByViagem_Call {
	_c.Call.Return(viagemHorarios, err)
	return _c
}

func (_c *MockViagemService_ListHorariosByViagem_Call) RunAndReturn(run func(ctx context.Context, viagemID int64) ([]viagens.ViagemHorario, error)) *MockViagemService_ListHorariosByViagem_Call {
	_c.Call.Return(run)
	return _c
}

// Resumo provides a mock function for the type MockViagemService
func (_mock *MockViagemService) Resumo(ctx context.Context) (viagens.ViagemResumo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Resumo")
	}

	var r0 viagens.ViagemResumo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (viagens.ViagemResumo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) viagens.ViagemResumo); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(viagens.ViagemResumo)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockViagemService_Resumo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resumo'
type MockViagemService_Resumo_Call struct {
	*mock.Call
}

// Resumo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockViagemService_Expecter) Resumo(ctx interface{}) *MockViagemService_Resumo_Call {
	return &MockViagemService_Resumo_Call{Call: _e.mock.On("Resumo", ctx)}
}

func (_c *MockViagemService_Resumo_Call) Run(run func(ctx context.Context)) *MockViagemService_Resumo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockViagemService_Resumo_Call) Return(viagemResumo viagens.ViagemResumo, err error) *MockViagemService_Resumo_Call {
	_c.Call.Return(viagemResumo, err)
	return _c
}

func (_c *MockViagemService_Resumo_Call) RunAndReturn(run func(ctx context.Context) (viagens.ViagemResumo, error)) *MockViagemService_Resumo_Call {
	_c.Call.Return(run)
	return _c
}
